### ISSUE TITLE
assign_wcs should populate WCS keywords for spectral axis

### ISSUE THREAD

**Issue by nden** [spacetelescope/jwst#1049]
SDP is not going to populate any of the spectral WCS keywords. Need t ofigure out what keywords assign_wcs needs to populate to have the spectral axis defined. WCSAXES should be changed to 3.

**Comment by hbushouse** [comment]
IIRC, in the past you had told me that assign_wcs needed to at least realize that it should be using WCSAXES=3, and to have CTYPE3 and CUNIT3 populated just so it knew how to initialize the 3rd axis. I don't think it needed to know anything about CRPIX3, CRVAL3, or CDELT3 (or PCm_n where either m or n=3). But I could be wrong ...

**Comment by nden** [comment]
@hbushouse That is correct. Is SDP populating CTYPE3, CUNIT3 and WCSAXES=3?

**Comment by hbushouse** [comment]
They will populate WCSAXES, but I think it'll now be set to a value of 2, because they'll only be providing 2 axes worth of the rest of the keywords (crpix, crval, cdelt, cunit, ctype, pcm_n). CTYPE3 and CUNIT3 will no longer be there. Do we need to have them set WCSAXES=3 (as they're currently doing), just so assign_wcs knows that a wavelength axis is needed, or would that cause problems due to the fact that none of the other axis 3 keywords will be there? Basically we'll need to use the same logic that they've used in the past to determine when WCSAXES should be 3 (e.g. a list of EXP_TYPES that indicate a spectroscopic mode).

**Comment by nden** [comment]
It may cause problems in some cases if WCSAXES=3 but none of the others is populated. If we are doing some of the 3rd axis keywords, let's do all of them in one place.

**Comment by hbushouse** [comment]
@nden status?

**Comment by nden** [comment]
assign_wcs does not do anything about this currently. The core schema has the 3rd axis keywords included so at least they will be there although they will have default generic values.

**Comment by hbushouse** [comment]
Slip to B7.2?

**Comment by nden** [comment]
Yah, if it's not a problem for 7.1.

**Comment by nden** [comment]
This is related also to #2262. The work on this is almost complete but it will have to be revised because of #2262. Closing this in favor of #2262.
