### ISSUE TITLE
NRC_TSGRISM source object location

### ISSUE THREAD

**Issue by sosey** [spacetelescope/jwst#1235]
The TSGRISM mode was implemented in assign_wcs using the the same general models as NRC_GRISM. However, this mode will always place the source object in the same detector position for each exposure. Since we know where the source should be, if we add this information to the meta information in the data model, we can update the gwcs models to include this information for the users.  #1232 includes the general implementation.

**Comment by hbushouse** [comment]
The NIRCam JDox (https://jwst-docs.stsci.edu/display/JTI/NIRCam+Grism+Time+Series) indicates that TS grism observations can use any of the SUBARRAY settings:
```
FULL
SUBGRISM64
SUBGRISM128
SUBGRISM256
```
All of which are confined to using the `GRISMR` grism, in conjunction with one of a few choices of FILTER. All grism exposures are confined to the `A5` detector, which is module A in the long-wave channel. All of the above subarrays have a dimension of 2048 pixels (full detector) in the direction parallel to the spectral trace. So the varying sizes are in the cross-dispersion direction and are there simply for the purpose of varying the readout times (smaller subarray = shorter readout). The resulting difference in the images is just more or less background area around the spectral trace.

The NIRCam SIAF has the following entries for those subarray apertures:
```
InstrName | AperName              | AperType | XDetSize | YDetSize | XDetRef | YDetRef | XSciSize | YSciSize | XSciRef | YSciRef | XSciScale | YSciScale | V2Ref | V3Ref | V3IdlYAngle | VIdlParity | DetSciYAngle | DetSciParity | V3SciXAngle | V3SciYAngle
NIRCAM    | NRCA5_GRISM256_F322W2 | SUBARRAY | 2048     | 2048     | 467.00  | 34.00   | 2048 | 256 | 1582.00 | 34.00 | 0.06388313 | 0.06447882 | 50.759071 | -556.422566 | 0.221332 | -1 | 0.0 | -1 | -90.143030 | 0.221332
NIRCAM    | NRCA5_GRISM128_F322W2 | SUBARRAY | 2048     | 2048     | 467.00  | 34.00   | 2048 | 128 | 1582.00 | 34.00 | 0.06388313 | 0.06447882 | 50.759071 | -556.422566 | 0.221332 | -1 | 0.0 | -1 | -90.143030 | 0.221332
NIRCAM    | NRCA5_GRISM64_F322W2  | SUBARRAY | 2048     | 2048     | 467.00  | 34.00   | 2048 | 64 | 1582.00 | 34.00 | 0.06388313 | 0.06447882 | 50.759071 | -556.422566 | 0.221332 | -1 | 0.0 | -1 | -90.143030 | 0.221332
NIRCAM    | NRCA5_GRISM256_F277W  | SUBARRAY | 2048     | 2048     | 467.00  | 34.00   | 2048 | 256 | 1582.00 | 34.00 | 0.06388313 | 0.06447882 | 50.759071 | -556.422566 | 0.221332 | -1 | 0.0 | -1 | -90.143030 | 0.221332
NIRCAM    | NRCA5_GRISM128_F277W  | SUBARRAY | 2048     | 2048     | 467.00  | 34.00   | 2048 | 128 | 1582.00 | 34.00 | 0.06388313 | 0.06447882 | 50.759071 | -556.422566 | 0.221332 | -1 | 0.0 | -1 | -90.143030 | 0.221332
NIRCAM | NRCA5_GRISM64_F277W | SUBARRAY | 2048 | 2048 | 467.00 | 34.00 | 2048 | 64 | 1582.00 | 34.00 | 0.06388313 | 0.06447882 | 50.759071 | -556.422566 | 0.221332 | -1 | 0.0 | -1 | -90.143030 | 0.221332
NIRCAM | NRCA5_GRISM256_F356W | SUBARRAY | 2048 | 2048 | 467.00 | 34.00 | 2048 | 256 | 1582.00 | 34.00 | 0.06388313 | 0.06447882 | 50.759071 | -556.422566 | 0.221332 | -1 | 0.0 | -1 | -90.143030 | 0.221332
NIRCAM | NRCA5_GRISM128_F356W | SUBARRAY | 2048 | 2048 | 467.00 | 34.00 | 2048 | 128 | 1582.00 | 34.00 | 0.06388313 | 0.06447882 | 50.759071 | -556.422566 | 0.221332 | -1 | 0.0 | -1 | -90.143030 | 0.221332
NIRCAM | NRCA5_GRISM64_F356W | SUBARRAY | 2048 | 2048 | 467.00 | 34.00 | 2048 | 64 | 1582.00 | 34.00 | 0.06388313 | 0.06447882 | 50.759071 | -556.422566 | 0.221332 | -1 | 0.0 | -1 | -90.143030 | 0.221332
NIRCAM | NRCA5_GRISM256_F444W | SUBARRAY | 2048 | 2048 | 1097.00 | 34.00 | 2048 | 256 | 952.00 | 34.00 | 0.06362050 | 0.06428569 | 90.908640 | -556.242528 | -0.320389 | -1 | 0.0 | -1 | -90.373035 | -0.320389
NIRCAM | NRCA5_GRISM128_F444W | SUBARRAY | 2048 | 2048 | 1097.00 | 34.00 | 2048 | 128 | 952.00 | 34.00 | 0.06362050 | 0.06428569 | 90.908640 | -556.242528 | -0.320389 | -1 | 0.0 | -1 | -90.373035 | -0.320389
NIRCAM | NRCA5_GRISM64_F444W | SUBARRAY | 2048 | 2048 | 1097.00 | 34.00 | 2048 | 64 | 952.00 | 34.00 | 0.06362050 | 0.06428569 | 90.908640 | -556.242528 | -0.320389 | -1 | 0.0 | -1 | -90.373035 | -0.320389
NIRCAM | NRCA5_GRISM_F322W2 | FULLSCA | 2048 | 2048 | 467.00 | 485.00 | 2048 | 2048 | 1582.00 | 485.00 | 0.06346680 | 0.06383978 | 50.876462 | -527.493218 | 0.245288 | -1 | 0.0 | -1 | -89.993439 | 0.245288
NIRCAM | NRCA5_GRISM_F277W | FULLSCA | 2048 | 2048 | 467.00 | 485.00 | 2048 | 2048 | 1582.00 | 485.00 | 0.06346680 | 0.06383978 | 50.876462 | -527.493218 | 0.245288 | -1 | 0.0 | -1 | -89.993439 | 0.245288
NIRCAM | NRCA5_GRISM_F356W | FULLSCA | 2048 | 2048 | 467.00 | 485.00 | 2048 | 2048 | 1582.00 | 485.00 | 0.06346680 | 0.06383978 | 50.876462 | -527.493218 | 0.245288 | -1 | 0.0 | -1 | -89.993439 | 0.245288
NIRCAM | NRCA5_GRISM_F444W | FULLSCA | 2048 | 2048 | 1097.00 | 485.00 | 2048 | 2048 | 952.00 | 485.00 | 0.06321445 | 0.06365699 | 90.768229 | -527.397936 | -0.237345 | -1 | 0.0 | -1 | -90.281801 | -0.237345
NIRCAM | NRCA5_TAGRISMTS32 | SUBARRAY | 2048 | 2048 | 782.00 | 260.00 | 32 | 32 | 16.50 | 16.50 | 0.06350811 | 0.06403240 | 70.844963 | -541.844075 | -0.024593 | -1 | 0.0 | -1 | -90.195743 | -0.024593
```
Despite the unreadable formatting, what this shows is that because these are all actual subarray readout patterns, including full-frame, they have complete SIAF entries for all parameters, including XSciRef, YSciRef, from which we populate the CRPIX1/2 keywords, and in turn tell us the location of the source (the assumption being that the source has been placed at the aperture reference point).

Also note that the XSciRef/YSciRef entires have 2 different sets of values: 1582 x 34 for the first set of subarrays, and 952 x 34 for the remainder. This is consistent with the JDox information that indicates two different source locations, depending on which subarray+filter combination is in use.

So we should be able to simply use the values of CRPIX1/2 as the source location in whichever cal pipeline steps needs that info (I'm guessing that's extract_2d).

**Comment by hbushouse** [comment]
This is high priority for B7.2, because it's needed to fulfill level 4 requirement DMS-786.

**Comment by sosey** [comment]
`extract_2d` doesn't currently accept NRC_TSGRISM, is it supposed to? I thought it skipped that step and went into the TSO3 pipeline and straight to `extract_1d`?  Updating the source object location for this mode would be done in `assign_wcs`. Unless teams want to keep the source location flexible.

**Comment by sosey** [comment]
It might be easier for `extract_1d` to just pull the source location from crpix1/2 and leave the wcs models flexible then, in case someone thinks the source ended up in a location other than the aperture pointed one

**Comment by sosey** [comment]
https://github.com/STScI-JWST/jwst/issues/1710 confuses me in this case, is that the request to implement `extract_2d` for NRC_TSGRISM?

**Comment by sosey** [comment]
worked out in #1710, will add extract_2d to TSO mode and use crpix and a set cross dispersion size

**Comment by hbushouse** [comment]
Given the different sized subarrays, including full frame, that can be used with the TSO grism mode, and the fact that the dispersion only covers a portion of the 2048 dimension of all the subarrays, we do in fact want to apply extract_2d to TSO grism data, in order to provide a cutout that only includes a useful region about the one source of interest. See #1710 for cutout details.
