### ISSUE TITLE
TSO processing in calwebb_detector1

### ISSUE THREAD

**Issue by karllark** [spacetelescope/jwst#1455]
The TSO observations need to have slightly different processing in calwebb_detector1 than the rest of the observations.
Specifically: ipc, first-frame, last-frame, and persistence corrections are never done for any instrument.
In addition, the corrected ramps (right before slope fitting) should be saved for TSO only by default.  All other observations should not save the corrected ramps.

**Comment by karllark** [comment]
I found a closed issue that seems to be a duplicate of this and implies that this work has already been done.  It is issue #1473.  If more knowledgeable people agree, please close this issue.

**Comment by hbushouse** [comment]
Issue #1400, and corresponding PR #1415, implemented the `calwebb_tso1.cfg` configuration file for use with the `calwebb_detector1` pipeline, which skips the ipc, last-frame, and persistence steps for all TSO exposures (regardless of instrument). So that covers everything mentioned here except for the first-frame step - which isn't implemented yet - and saving the corrected ramp (4-D) data. Those would need to be added in a subsequent update. So we should leave this issue open for now and assign it to B7.2 for implementation, along with the first-frame step.

**Comment by karllark** [comment]
Good points.  Sounds like a plan!

**Comment by hbushouse** [comment]
Fixed by #2280
