### ISSUE TITLE
naming of source-based files

### ISSUE THREAD

**Issue by stscieisenhamer** [spacetelescope/jwst#159]
How will the source based data be named? Possible sources:
- MultiSlitModel.slit.name
- MultiSlitModel.slit.slitlet_id
- MultiSlitModel.slit.source_id
- Same combination involving filenames.

**Comment by stscieisenhamer** [comment]
@hbushouse Thoughts?

**Comment by hbushouse** [comment]
The exp_to_source task will be run as essentially the first step of the calspec3 pipeline, at least for some observing modes, i.e. the ones that obtain spectra of multiple sources simultaneously (which means NIRCam and NIRISS WFSS, NIRSpec MOS, and NIRSpec fixed-slit). The input to the calspec3 pipeline will be a level-3 ASN table, which will list all the input level-2b exposure-based products. Because the ASN generator can't know at the time it runs what the various output sources will be and hence it can't specify the output source-based file name(s) in the ASN table, either the calspec3 pipeline module or the exp_to_source task itself will need to construct the source-based output file names. The ASN generator could at least specify a template source-based file name in the ASN table, such as:

"jw12345_o0001_<targ_id/source_id>_nirspec_g140m_<prod_type>.fits"

and then leave it to either calspec3 or exp_to_source to fill in both <targ_id/source_id> and <prod_type> as each source-based file is created. For WFSS and MOS modes, we should have an actual source_id available for each source from the WFSS source catalog or the MSA meta data table, respectively. Those names could easily be stored in the SOURCEID keyword for each slit instance that was created upstream in calspec2 during the extract_2d step, and hence that's where exp_to_source can get them. The NIRSpec fixed-slit case is not as straightforward, because we won't have individual source id's specified upstream for each slit. I think the best that can be done for that mode is to use the generic target_id from the exposures (which should be the same for all input exposures) and perhaps append the slit name (S200A1, S200B1, etc.) as an additional part of either the target_id field or the optical element field of the output source-based file name.

**Comment by stscieisenhamer** [comment]
Resolved by #2330
