### ISSUE TITLE
Extract specific orders for WFSS data

### ISSUE THREAD

**Issue by sosey** [spacetelescope/jwst#1756]
See also https://jira.stsci.edu/browse/JP-204

From Kevin Volk:

> For NIRISS WFSS we want the first order spectra extracted for all filters, and also the second order spectrum extracted for the F090W filter only. The second order spectra for the other filters F115W to F200W are quite faint and assumed to be not worth extracting or calibrating. Similarly, the order -1 and order 3 spectra are generally rather faint and there was no plan to extract and calibrate these orders routinely in the pipeline, although for bright sources one might want to extract these orders, and also for bright sources we need to know where these orders are to model spectral overlap. For a really bright source some of the ground test data shows orders 4 and higher for some cases where were really blasting the array with a very bright point source, but these grow progressively fainter and for science exposures it is unlikely that something that bright will ever be in the field of view. The “extra” orders would not be processed in the pipeline.

There are a few ways we could go about implementing this, a combination of methods might prove the most flexible:

**1. add information on orders to be extracted to the `specwcs` reference file, this reference file is instrument specific.** 

This reference file is also specific to the grism and the pupil/filter, so a new data member could effectively just be a list of orders to extract by default. 

> `instrument:` {detector: NIS, filter: GR150R, name: NIRISS, pupil: F200W}`

The orders that are available (have defined polynomials) in the reference file itself are listed under the `orders` member:

> `orders: [1, 0, 2, 3, -1]`

This method would require updates to the class code to pull in what was specified in the reference file

**2.  Add parameter to the processing class for assign_wcs that specifies what orders and wavelengths should be used.**

- `assign_wcs` takes in the `specwcs` and `wavelengthrange` reference files
- `extract_2d` currently only looks for the `wavelengthrange` reference file

`extract_2d` requires the WCS object already exists, the WCS object already contains information on the orders that are available, this could be modified at the start of `assign_wcs` to represent only the requested orders, not all available orders.

-- At the pipeline level -- 

**3. Add parameters to the cfgspec file for the step that specifies what orders per filter should be extracted.**

We would need one that accepts a dictionary keyed by filter, or a list of lists, or for the caller to only provide data (single files or an asn of files) that only pertain to one filter+grism combination.
I'm not sure I see more that string, bool, int, and list as available datatypes in the configobj specification for the cfg files in stpipe (@stscieisenhamer?) 

This method, when considered by itself, would require a change to the input step parameters so that the information could be passed down from the step level. 

* precedence for processing would be whatever is specified in the `specwcs` reference file, unless something else is specified for the class parameter, so the class parameters would need reasonable defaults to decide (None or empty) what applies

**Comment by hbushouse** [comment]
Regarding #2 above, if we modify assign_wcs to only load WCS info for the orders to be extracted, then if someone wants to "play" with extracting different order they have to rerun assign_wcs to make it happen. If, however, assign_wcs continues to load info for all orders available in the specwcs ref file, then someone could just rerun extract_2d and tell it which orders to actually extract. Would having the additional (unnecessary) order info always loaded by assign_wcs cause any inefficiency downstream? (as opposed to only loading the order info that's needed for a given run). Of course that means somehow modifying extract_2d (or it's config file) to allow specification of which orders to extract, instead of having it always extract all orders that exist within the WCS object.

**Comment by hbushouse** [comment]
We could also get conflicts if we went with a scheme that puts the default orders to extract in the specwcs ref file, which is then used by assign_wcs to load only WCS info for those orders, and then allow a user-settable param on the extract_2d step for overriding the default orders. For example, if someone runs with the defaults, such that info for only orders 1 and 2 (for example) get loaded during assign_wcs and then tries to rerun extract_2d by itself with the user param set to orders 1, 2, and 3, it's going to barf, because there's no info in the WCS object for order 3.

So that again argues for a scheme in which assign_wcs always loads all orders into the WCS object, but also sets some kind of additional attribute (read in from specwcs) that tells downstream steps like extract_2d which orders to actually extract (e.g. only 1 and 2, even though info is available for all orders). That way if/when a user goes back and reruns only extract_2d and specifies more orders to extract, the needed info will be there in the WCS object.

**Comment by stscieisenhamer** [comment]
In option 3, with respect to the cfg and handling of dicts, I believe the default ConfigObj does not handle dict. If there is need, the validator can be extended to handle dict. However, it may just be as easy as defining different parameters per instrument/filter, or a string that would `ast.literal_eval` to the dict.

Again, in option 3, there is a comment about "passing down" information from the step level: If the passing down is from a higher-level step or pipeline, to a called step, there is a relatively new method to `Step`, call [`search_attr`](https://github.com/STScI-JWST/jwst/blob/master/jwst/stpipe/step.py#L503), which will return an attribute/configuration parameter found anywhere in the step heirarchy, not just from a `Step`s immediate attribute/configuration.

**Comment by hbushouse** [comment]
I think if we use a hybrid of all 3 options we can do it without requiring instrument+filter-specific order listings in the cfg file. For example, keep the `orders` attribute that's already in the specwcs file to indicate which orders are defined in that ref file, and add another attribute that's something like `extract_orders`, which could be filter-dependent if necessary, and lists the default orders to be extracted. The info for all orders in the specwcs ref file gets loaded by assign_wcs, along with the `extract_orders` attribute. Now also add a new param to the extract_2d step that by default is set to `orders_to_extract = None`. When extract_2d gets run, it sees that `orders_to_extract` is None and so uses the default set of orders (`extract_orders`) that got carried along in the WCS object from the specwcs ref file. If extract_2d sees that its param `orders_to_extract` is not None, then it uses the list of numbers specified in that param (overriding whatever came from the specwcs file). Of course it would also need to verify that it's actually got WCS info for all of the orders requested.

That way the new extract_2d step param can just be a simple param (perhaps a list), rather than something complicated like a filter-dependent dictionary.

Thoughts?

**Comment by hbushouse** [comment]
This issue is a high priority fix relative to B7.1, because it is in essence a failure of the requirement to produce calibrated products for NIRCam and NIRISS WFSS modes, which was delivered in B7.1.

**Comment by sosey** [comment]
producing too many calibrated products is a failure? Interesting....in any case, this is on my list for today.

**Comment by hbushouse** [comment]
It's only a failure in the sense that it's not what INS wants and hence doesn't match the specs. That's what happens when you get the specs after writing the code ...

**Comment by philhodge** [comment]
This also affects `extract_1d`, because that has to loop over the available spectral orders.

**Comment by sosey** [comment]
Yes, but by the type extract_1d get to the data, you're dealing with just the extracted 2D arrays, and only the orders that were requested were extracted, so I'm not sure anything specific needs to be done to extract_1d in these cases?

**Comment by hbushouse** [comment]
That sounds right: the product being used as input to extract_1d should only have data for those orders extracted by extract_2d and hence should be able to just loop over whatever slit instances it's been given (assuming that I actually understand how this works).

**Comment by sosey** [comment]
Yup. Phil was mostly worried about how this PR might affect NIRISS SOSS mode, but I don't think it should have any effect. If it does, we should discuss :-)

**Comment by sosey** [comment]
@hbushouse this was requested by NIRISS, but the code will be able to do this for NIRCAM WFSS as well. @nprizkal does NIRCAM have a wish to only extract, by default, specific spectral orders for all or a selection of blocking filters?

**Comment by hbushouse** [comment]
In addition to only extracting desired orders, testing of B7.1 showed some peculiarities in the extraction region limits computed by extract_2d, for example:
```
2018-01-10 08:11:42,402 - stpipe.Spec2Pipeline.extract_2d - INFO - Subarray extracted for obj: 1 order: 1:
2018-01-10 08:11:42,402 - stpipe.Spec2Pipeline.extract_2d - INFO - Subarray extents are: (xmin:636, ymin:948), (xmax:644, ymax:936)
2018-01-10 08:16:48,533 - stpipe.Spec2Pipeline.extract_2d - INFO - Subarray extracted for obj: 1 order: 2:
2018-01-10 08:16:48,534 - stpipe.Spec2Pipeline.extract_2d - INFO - Subarray extents are: (xmin:460, ymin:747), (xmax:437, ymax:700)
```
where the min values are greater than the max values. This may have to do with the fact that the dispersion direction is running right to left (or top to bottom)? We need to make sure that the actual 2D regions being extracted are not being affected by this apparent anomaly. This particular oddity was also discussed in the original basecamp thread at: 
https://stsci-ins.basecamphq.com/projects/11477312-jwst-pipeline/posts/104432125/comments
and is being tracked by INS in JIRA ticket https://jira.stsci.edu/browse/JP-206

**Comment by philhodge** [comment]
The subarray extents also look too small to contain spectra.  Was `extract_2d` run on the direct image, rather than on the dispersed image?
