### ISSUE TITLE
TST: CI overhaul

### ISSUE THREAD

**Issue by pllim** [spacetelescope/jwst#1913]
Follow up of #1888 and all the good stuff it now enables:

- [ ] Make sure `install_requires` or `tests_require` include `astropy` and `numpy` in `setup.py`.
- [ ] Replace Travis CI with another Jenkins instance that runs test per push event (#1462). Also add a badge or link to README.
- [ ] Only pull dependencies as needed from `conda-dev`. Default channel should  be `astroconda` because that is what we deliver.
- [ ] Refactor fixtures to support 3 use cases -- https://github.com/STScI-JWST/jwst/pull/1888#discussion_r182173199
- [ ] Revisit usage of `_jail` fixture -- https://github.com/STScI-JWST/jwst/pull/1888#discussion_r182178849
- [ ] Consolidate individual test helpers into one.
- [ ] Tests are to use common utility functions from test helper, e.g., for comparing FITS. There is already some sort of general function at https://github.com/STScI-JWST/jwst/pull/1888#discussion_r182187353
- [ ] Use `with fits.open(filename) as h` context manager instead of `h = fits.open(filename)`.
- [ ] Replace `from astropy.io import fits as pf` simply with `from astropy.io import fits`.
- [ ] Use Artifactory for "bigdata" when it is available.
- [ ] Using `os.path.join` for path constructions, instead of `path1 + path2 + file`.
- [ ] Developers who wrote those tests should better document the tests (e.g., purpose, input, output, expected behavior, etc).
- [ ] Developers who wrote affected tests should eliminate undocumented magic numbers -- https://github.com/STScI-JWST/jwst/pull/1888#discussion_r182181098 
- [ ] Delete commented (dead) code from tests.
- [ ] Delete obsolete `pandokia`-specific code -- https://github.com/STScI-JWST/jwst/pull/1888#discussion_r182186927
- [ ] Replace `list(range(...))` simply with `[0]` or `[0, 1]` as applicable -- https://github.com/STScI-JWST/jwst/pull/1888#discussion_r182182131
- [ ] Stop using deprecated `from numpy.testing import utils`. This won't work for `numpy>=1.15`.
- [ ] Investigate why the one test ran for over 4 hours and if it is possible to scale it down -- https://github.com/STScI-JWST/jwst/pull/1888#discussion_r182186142
- [ ] Write developer doc on how to add new test. Idea: A new section in your RTD doc with an example template test file content.

Phew.

**Comment by jdavies-st** [comment]
> Only pull dependencies as needed from conda-dev. Default channel should be astroconda because that is what we deliver.

The reason we build nightly astroconda-dev snapshots is so developers and users can get a latest working codebase.

If we want to pin some dependencies in this nightly snapshot to a delivered or stable version of `astropy` or `numpy`, then maybe we can discuss that?  But often GWCS or something else requires the latest master dev of `astropy`.

What problem or issue are we trying to resolve here?

Everything else in the list looks great!

**Comment by sosey** [comment]
I would really like NOT to pin astropy or numpy for  conda-dev.

we deliver astronconda-contrib, not conda-dev

As James points out, we need somewhere to test code against development masters of many packages. Once the jwst pipeline is officially released, that released code will be part of astroconda-contrib

**Comment by pllim** [comment]
> What problem or issue are we trying to resolve here?

Solving problem of not catching backward incompatible changes (as you test against latest and greatest only) until you push to `astroconda-contrib`, where things might not be latest and greatest yet.

**Comment by sosey** [comment]
There's no reason we can't have more jenkins or travis-ci tests that test against the package versions in contrib...I still want the tests run against the dev-master specified conda-dev dependency environment.

**Comment by pllim** [comment]
> There's no reason we can't have more jenkins or travis-ci tests

Well, given a full test suite is like 2-6 hours long and limited resources currently, while it is nice, you can't probably run a full suite in a full matrix. Anyway, that was just some recommendation from my side. Feel free to ignore if they don't apply.

**Comment by jdavies-st** [comment]
Yeah, I like the idea of testing against different versions for backwards compatibility.  In the past, our test matrix for unit tests on Travis CI often had 2 or more versions of `numpy`.  But usually for `astropy`, we need the latest `master` for the JWST pipeline to run.  For these nightly tests, perhaps it is not possible to do this due to time constraints.

We actually do deliver astroconda-dev, right?  Or at least the build recipe is basically the same between astroconda-dev nightly build and our DMS builds?  @rendinam ?

**Comment by sosey** [comment]
When I say "deliver" above I'm referring to the public release that goes into astroconda-contrib, apologies, I should have been more precise.

We deliver the conda-dev code+env to DP so that they can validate installs and releases for HST and JWST pipeline code. We need to send them the environment we are using and testing against,  code that is approved for the pipelines by DP can then be released through astroconda-contrib. It's often important not to release pipeline code into astroconda-contrib before it's approved by DP (AND the data has been reprocessed) because sometimes meta information needed by the pipeline has to first be added into the raw data input to the pipeline. 

agreed that testing should be as backwards compatibile as possible in the light of all this.

**Comment by pllim** [comment]
Can we go ahead and go full Jenkins on this repo (item 2)? No reason to have to maintain two different CI settings when only one will cover all your use cases now. cc @jhunkeler @rendinam
