### ISSUE TITLE
what is the definition of version?

### ISSUE THREAD

**Issue by stscieisenhamer** [spacetelescope/jwst#2014]
In light of operations like #2013, what does `version` mean? In particular, is there a reason for version in each module?, or would having one `version` satisfy need/requirements? and don't commits update some version id somewhere also?

only requirement i see is having whatever version accessible to running code so that version can be written into meta information in output files and used by logging.

**Comment by jaytmiller** [comment]
I had a few comments on version:
1. I think it's being tracked on the Step level.
2. There's a level-4 requirement / interface with the AUI to provide a service defining CAL s/w versions.
3. As such,  I think the intent was to inform users of changes to Steps and possible impacts to their data processing.
4. The scheme is somewhat arbitrary and disassociated from other more technical forms of versioning like git tags or hashes...  but while those might be used to formally recreate a CAL installation,  they're less useful a the user level to give an immediate indication about changes to Steps.
5. Because the existing versioning scheme is part of a service interface with the AUI,  changes to the definition of version need to be coordinated with the AUI.
6. The current scheme feeds into the automatic generation of the SYSTEM CALVER reference file defined for each build and used to drive the AUI service interface.  Once the CAL s/w matures version should probably not change for every Step for every build,  only for those Steps which receive updates.

**Comment by stscieisenhamer** [comment]
Can someone post the exact wording of this Level 4 requirement?

**Comment by hbushouse** [comment]
There are several that are related to versioning:

DMS-54: "There shall be a traceable history for all processed data that includes at least   the following:
 a) A list of the original data sets          
 b) Each processing step applied to the data        
 c) Identification of the software **version** used for processing the data        
 d) The software configuration (options invoked or disabled, software switch settings, control parameters, etc.)        
 e) A list of any ancillary data used in processing"

DMS-547: "CRDS shall provide a tool to show the set of active reference files being used for all supported versions of the software, or a specific version of the software."

DMS-592: "The Archive User Interface shall show the current version number for each calibration step of an observation."

DMS-594: "Header keywords shall reflect the software version of each calibration step used to   process the data file."

**Comment by jdavies-st** [comment]
I think one needs a deep knowledge of the pipeline to know that a change in the version of `assign_wcs` may have a big effect on the output of `calwebb_image3`, even though the version of `calwebb_image3` didn't change.  Or if the version of `assign_wcs` did change, but only for spectroscopic data, a version would not help you know whether the output of the pipeline has or should have changed.

So there's no way unless you look at a changelog (which we currenly do not do) to know what versions of what steps impact what data.  And even then, it may not be clear.

So that can't be the reason for recording these versions.

Rather, the reason has to be so that the processing is reproducible. But reproducibility really only can be guaranteed by processing the same input data with the same references files in the complete `jwst` package at the same git commit hash.  (And the same upstream dependencies, but let's not get into that.)

I think we should be putting the `jwst` package version number in all the subpackage `__version__` strings and dispense with separate step versions.

**Comment by jaytmiller** [comment]
Digressing based on Howard's requirements,   I've always interpreted s/w version here:

_DMS-547: "CRDS shall provide a tool to show the set of active reference files being used for all supported versions of the software, or a specific version of the software."_

as "list references by context."       

CRDS has a command line tool (crds list) and web features to show references within a context and the history of active contexts.    The active or past references can be browsed.  The list of references for a list of contexts can be dumped to stdout.    Dates can be translated to contexts.

Why doesn't  DMS-547 make much sense to me?   During say the 3 month shelf-life of a CAL release,  a quarterly build,  the pipeline will go through 15-30 different contexts.   So "active set" is not really dependent on a CAL_VER.  Active set is defined by constantly changing contexts while CAL_VER is fixed.   For past releases about as good as "active" gets is "the last context we used."   

CRDS_CTX exists for the sake of real repeatability as do the R_ keywords.   

If anyone has some other reasonable interpretation of DMS-547,  we can look at supporting it.   We would just need to define "set of active reference files" and "supported versions of the software" and learn how to translate versions of software to contexts.

**Comment by hbushouse** [comment]
@jdavies-st I couldn't agree more with your assessment (funny how you pick up on things so fast!). This has been a years-long debate, with developers raising exactly these kinds of issues. There are many steps that do things completely differently for different exposure types or instruments and hence there's no one-to-one correlation between version number and how it affects **my** data. The Level-4 requirements were written many years ago from a very high-level view of how things work in the actual pipeline. We at least got people to agree to NOT putting a version number keyword for EVERY step in the output products, but instead use the single keyword ``CAL_VER`` to indicate the overall package version number, along with the more detailed git-based version (not quite hash-like) info stored in the ``CAL_VCS`` keyword. From the value of ``CAL_VER`` it's possible to list the version numbers of each step/subpackage within jwst, which archive can use to satisfy their requirement to show the versions of each step used.

**Comment by stscieisenhamer** [comment]
Sooo...understood that all things in the package may affect all other things, and that all of the DMS requirements are actually satisfied, at least to the letter, this seems to be just a policy question.

Re-framing the question then: What is SCSB's policy on versioning?  Possible options are:
- One version: This is what is actually being done, since, on release, all versions are set to a common value. Implemented in a semi-automatic way where it is changed in one spot, and reference to `version` of any submodule simply returns this one value.
- Support **Step versioning**: Could be handled through a formal PR review process (yes, I went there), in which some general rules are used to determine which (or all) submodules get a version bump.
- ???

**Comment by jaytmiller** [comment]
Jonathan and I discussed this some offline in terms of the implications it might have for CRDS.    In the end we decided we should probably leave the existing reference file + CRDS web service "AUI delivery architecture" alone and limit the scope of this issue to JWST CAL Step version policy,  for which CRDS is agnostic rather than bored.

My only remaining comments are:  (a)  build-by-build,  we'll still need to generate the SYSTEM CALVER reference to reflect whatever Step version policy we choose to define.   I think the semantics are up to us until someone asks for something else.    (b) any change in Step version string relative to what we have now  (e.g. switch to git hash vs. x.y.z) could unintentionally impact the AUI.  So syntactically,  we should exercise caution and coordinate with the consumer some.

**Comment by mkyp** [comment]
I've added this topic for discussion at the next DMS design meeting.

Can someone comment how the versioning for each step is currently being set?  I see a  version for each of cal, sdp and crds. And the cal steps are listed as "complete, skipped, etc"

NOTE:  all 4 of the DRs  (DMS-54, DMS-547, DMS-592 and DMS-594) mentioned in this ticket have already been delivered and verified...

**Comment by jaytmiller** [comment]
Versioning of Steps is defined in the CAL code for each Step.

Versioning of Steps is communicated to the AUI by (a) generating the CRDS SYSTEM CALVER reference file which records Step versions using a CAL script and (b) presenting the contents of the reference file to the AUI using a JSONRPC web service keyed on the master CAL_VER version, e.g. 0.9.5.   This JSONRPC interface is why version syntax can potentially affect the archive and cannot be changed arbitrarily.    CAL_VER is recorded in the datasets.

The Step versions as defined by CAL and tracked by CRDS are as accurate as we want (have time) to make them,  with the primary I&T driver being delivering to the archive and/or pipeline.  Pipeline deliveries are not functionally required,   but modifying the CAL code + CRDS content requires regressing and archiving as a matter of being careful.

More on CRDS and DMS-547:

Reviewing DMS-547 and DMS-TP-441 for CRDS,  it was passed based on looking at the CRDS server context display .  I documented my interpretation/implementation of DMS-547 in Trac here:  https://aeon.stsci.edu/ssb/trac/crds/ticket/259 which also notes the Context History and "crds list" command line tool.   Strictly speaking,  associating a CAL_VER with a single context only makes sense during I&T when no CRDS testing is occurring.   Operationally,  it makes no sense since many CRDS contexts are generated per quarter / CAL_VER.   Consequently,  CRDS listing of reference files is date-based or context based.

**Comment by jdavies-st** [comment]
The versioning for each step is being set manually in the `__init__.py` file for each pipeline step.  See PR #2013 linked at the start of this discussion.

Once that version is set in the `__init__.py` file for each step, then it gets propogated as @jaytmiller mentions above.

But right now we just doing this manually, and this version doesn't map to any actual changes in each step.  I.e. before delivery, all steps were incremented, regardless if they changed or not. Same with the library code `stpipe` and `datamodels`.

It would be easy to automate this and replace the line in each step's `__init__.py` file with some automatically-generated version number that is pulled from the tag/commit info of the `jwst` repo as a whole.

**Comment by hbushouse** [comment]
The scheme of "update the version number of all steps to the same value just before a release" was adopted back when we first implemented the capability to extract and store the version numbers from each step, due to the fact that at that time a lot of developers had used different ways of versioning the steps they worked on and hence we had a very inhomogeneous collection of version numbers scattered throughout the jwst package. We "rebaselined" all of them to bring them into conformity (this happened back at version 0.7.0 or thereabouts). We then unfortunately continued this practice for the last couple of builds/releases, which artificially incremented the version numbers of all steps regardless of whether or not they had changed. At the very least, we need to stop this practice for future releases (don't increment unless it's actually changed).

**Comment by stscicrawford** [comment]
As an update, I have a request to possible change the requirement or at least how we meet the requirement.  If it goes through, we would remove the version from each step, but we would still keep a list of steps and the last version of the software in which they were changed.   This should be possible to generate this from the git log.

**Comment by stscicrawford** [comment]
Okay this is now confirmed:    

1.  We can remove version in each individual step.   
2. The version in the reference file for the version of each step can be automatically generated from the gitlog as the last version number in which that step changed. 

There will be no rush in completing those tickets although they should be done for 7.2, but I'll open up two new tickets for updating those, but this should close off this question.
