### ISSUE TITLE
DQ extensions in refpix CRDS files

### ISSUE THREAD

**Issue by stscicrawford** [spacetelescope/jwst#2183]
@hbushouse commented in #2100 asking about refpix reference files:

Also, I notice that the actual ref files in CRDS have a "DQ" extension too. Are those necessary and/or used? If so, they should be documented here too.

The documentation in docs/jwst/refpix/reference_files.rst should be updated if necessary

**Comment by philhodge** [comment]
Are you talking about the IRS2 reference files?  If so, the current ones do not have a DQ extension.  The two files that do have DQ extensions have USEAFTER = '2000-01-01T00:00:00'.  The DQ in those two files are tables (BINTABLE), and I get an exception when I try to read them:

    TypeError: Cannot cast ufunc add output from dtype('float64') to dtype('uint32') with casting rule 'same_kind'

**Comment by jaytmiller** [comment]
Huh.   For a long time,  CRDS like CDBS did not have array data based checks,  the primary focus of certify was making sure CRDS rules updates and basic keywords were viable.   CRDS has array based checks now,  and should require INT-like DQ,   I'm pretty sure these were not the only FLOAT DQ arrays because certify pointed it out once or twice.   (Makes me wonder if INT-like int32 will cast correctly to uint32 either...)

For REFPIX,  I didn't see DQ in my last round of certify updates,  but my main focus was working on array dimension checks and not breaking anything,  not defining new constraints until the spec is consolidated and updated.

Due to generic SUBARRAY checks,   I think CRDS would now reject most or all of the current NIRSPEC REFPIX files,  because they define SUBSIZE1=3200.  I thought that was supposed to be limited to 2048.   Since they're tables,  my strategy of "if subarray keywords are defined,  check them" may be falling apart.   Do subarray keywords have any application to tables?

**Comment by philhodge** [comment]
That's interesting.  I had never noticed that SUBSIZE1 was 3200, probably because IRS2 data are always full-frame, and the step doesn't check those keywords (though it does check for non-IRS2 data).
I don't know what the DQ extensions in IRS2 reference files were supposed to be.  There may be some tables for which the subarray limits would be relevant, but I don't think of any off-hand.

**Comment by hbushouse** [comment]
The docs did not need updating, because the `irs2` data model (`refpix` reference file) only contains a table extension; no DQ array. The final issue of reworking the `irs2` data model schema has been fixed by #2295. Closing.
