### ISSUE TITLE
DOC: RTD choked at conda env

### ISSUE THREAD

**Issue by pllim** [spacetelescope/jwst#2190]
RTD builds have been consistently failing at `conda env build ...` for the last several builds.

https://readthedocs.org/projects/jwst-pipeline/builds/

**Comment by stscicrawford** [comment]
Looks like a problem in outlier detection and using stsci in the traceback:

Failed to import 'jwst.wiimatch.lsq_optimizer': no module named jwst.wiimatch.lsq_optimizer

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/jwst-pipeline/conda/latest/lib/python3.6/site-packages/sphinx/cmdline.py", line 303, in main
    args.warningiserror, args.tags, args.verbosity, args.jobs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/jwst-pipeline/conda/latest/lib/python3.6/site-packages/sphinx/application.py", line 233, in __init__
    self._init_builder()
  File "/home/docs/checkouts/readthedocs.org/user_builds/jwst-pipeline/conda/latest/lib/python3.6/site-packages/sphinx/application.py", line 311, in _init_builder
    self.emit('builder-inited')
  File "/home/docs/checkouts/readthedocs.org/user_builds/jwst-pipeline/conda/latest/lib/python3.6/site-packages/sphinx/application.py", line 444, in emit
    return self.events.emit(event, self, *args)
  File "/home/docs/checkouts/readthedocs.org/user_builds/jwst-pipeline/conda/latest/lib/python3.6/site-packages/sphinx/events.py", line 79, in emit
    results.append(callback(*args))
  File "/home/docs/checkouts/readthedocs.org/user_builds/jwst-pipeline/conda/latest/lib/python3.6/site-packages/sphinx_automodapi/automodsumm.py", line 255, in process_automodsumm_generation
    lines = automodsumm_to_autosummary_lines(sfn, app)
  File "/home/docs/checkouts/readthedocs.org/user_builds/jwst-pipeline/conda/latest/lib/python3.6/site-packages/sphinx_automodapi/automodsumm.py", line 327, in automodsumm_to_autosummary_lines
    filestr = automodapi.automodapi_replace(fr.read(), app, True, docname, False)
  File "/home/docs/checkouts/readthedocs.org/user_builds/jwst-pipeline/conda/latest/lib/python3.6/site-packages/sphinx_automodapi/automodapi.py", line 277, in automodapi_replace
    modnm, toskip, onlylocals=onlylocals)
  File "/home/docs/checkouts/readthedocs.org/user_builds/jwst-pipeline/conda/latest/lib/python3.6/site-packages/sphinx_automodapi/automodapi.py", line 388, in _mod_info
    for localnm, fqnm, obj in zip(*find_mod_objs(modname, onlylocals=onlylocals)):
  File "/home/docs/checkouts/readthedocs.org/user_builds/jwst-pipeline/conda/latest/lib/python3.6/site-packages/sphinx_automodapi/utils.py", line 78, in find_mod_objs
    __import__(modname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/jwst-pipeline/checkouts/latest/jwst/outlier_detection/__init__.py", line 2, in <module>
    from .outlier_detection_step import OutlierDetectionStep
  File "/home/docs/checkouts/readthedocs.org/user_builds/jwst-pipeline/checkouts/latest/jwst/outlier_detection/outlier_detection_step.py", line 7, in <module>
    from . import outlier_detection
  File "/home/docs/checkouts/readthedocs.org/user_builds/jwst-pipeline/checkouts/latest/jwst/outlier_detection/outlier_detection.py", line 6, in <module>
    from stsci.image import median
ModuleNotFoundError: No module named 'stsci'

Exception occurred:
  File "/home/docs/checkouts/readthedocs.org/user_builds/jwst-pipeline/checkouts/latest/jwst/outlier_detection/outlier_detection.py", line 6, in <module>
    from stsci.image import median
ModuleNotFoundError: No module named 'stsci'
The full traceback has been saved in /tmp/sphinx-err-gcjk7y6u.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!

**Comment by jdavies-st** [comment]
@stscicrawford Where can this traceback be found?

I've built the docs locally without problems, so this may be some problem for RTD not having all the dependencies it needs?  Not sure.

**Comment by sosey** [comment]
or import order as we've seen in other packages perhaps

**Comment by stscicrawford** [comment]
I think I was looking at this build:
https://readthedocs.org/projects/jwst-pipeline/builds/7382689/

However recent builds look to be having a problem with the environment.   I'd also try to do a build in a clean environment as there might be things in your path that aren't in the RTD environment.

**Comment by nden** [comment]
I pushed a change, we'll see if it's sufficient to fix the problem/

**Comment by jdavies-st** [comment]
Right now it is choking on the conda env creation.  The command
`conda env create --name latest --file /home/docs/checkouts/readthedocs.org/user_builds/jwst-pipeline/checkouts/latest/.rtd-environment.yml` creates the environment.  A week ago it was successfully creating the evironement [here](https://readthedocs.org/projects/jwst-pipeline/builds/7366950/):
```
sphinx_rtd_the   0% |                              | ETA:  --:--:--   0.00  B/s
sphinx_rtd_the  Collecting sphinx-automodapi
  Downloading https://files.pythonhosted.org/packages/c6/be/7b24d806568a76d839f4ae0e84edcb71b7e5aa0f958d5bf35ec76acad648/sphinx_automodapi-0.7-py2.py3-none-any.whl (62kB)
Collecting stsci_rtd_theme
  Downloading https://files.pythonhosted.org/packages/36/47/0a086a9a094e98da05f9c23c3ff636aa21e00c99994559ffb47ef781f34b/stsci_rtd_theme-0.0.1-py3-none-any.whl (79kB)
Requirement already satisfied: sphinx>1.3 in /home/docs/checkouts/readthedocs.org/user_builds/jwst-pipeline/conda/latest/lib/python3.6/site-packages (from sphinx-automodapi)
Requirement already satisfied: requests>=2.0.0 in /home/docs/checkouts/readthedocs.org/user_builds/jwst-pipeline/conda/latest/lib/python3.6/site-packages (from sphinx>1.3->sphinx-automodapi)
Requirement already satisfied: packaging in /home/docs/checkouts/readthedocs.org/user_builds/jwst-pipeline/conda/latest/lib/python3.6/site-packages (from sphinx>1.3->sphinx-automodapi)
Requirement already satisfied: docutils>=0.11 in /home/docs/checkouts/readthedocs.org/user_builds/jwst-pipeline/conda/latest/lib/python3.6/site-packages (from sphinx>1.3->sphinx-automodapi)
Requirement already satisfied: setuptools in /home/docs/checkouts/readthedocs.org/user_builds/jwst-pipeline/conda/latest/lib/python3.6/site-packages (from sphinx>1.3->sphinx-automodapi)
Requirement already satisfied: Jinja2>=2.3 in /home/docs/checkouts/readthedocs.org/user_builds/jwst-pipeline/conda/latest/lib/python3.6/site-packages (from sphinx>1.3->sphinx-automodapi)
Requirement already satisfied: six>=1.5 in /home/docs/checkouts/readthedocs.org/user_builds/jwst-pipeline/conda/latest/lib/python3.6/site-packages (from sphinx>1.3->sphinx-automodapi)
Requirement already satisfied: alabaster<0.8,>=0.7 in /home/docs/checkouts/readthedocs.org/user_builds/jwst-pipeline/conda/latest/lib/python3.6/site-packages (from sphinx>1.3->sphinx-automodapi)
Requirement already satisfied: snowballstemmer>=1.1 in /home/docs/checkouts/readthedocs.org/user_builds/jwst-pipeline/conda/latest/lib/python3.6/site-packages (from sphinx>1.3->sphinx-automodapi)
Requirement already satisfied: sphinxcontrib-websupport in /home/docs/checkouts/readthedocs.org/user_builds/jwst-pipeline/conda/latest/lib/python3.6/site-packages (from sphinx>1.3->sphinx-automodapi)
Requirement already satisfied: imagesize in /home/docs/checkouts/readthedocs.org/user_builds/jwst-pipeline/conda/latest/lib/python3.6/site-packages (from sphinx>1.3->sphinx-automodapi)
Requirement already satisfied: babel!=2.0,>=1.3 in /home/docs/checkouts/readthedocs.org/user_builds/jwst-pipeline/conda/latest/lib/python3.6/site-packages (from sphinx>1.3->sphinx-automodapi)
Requirement already satisfied: Pygments>=2.0 in /home/docs/checkouts/readthedocs.org/user_builds/jwst-pipeline/conda/latest/lib/python3.6/site-packages (from sphinx>1.3->sphinx-automodapi)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /home/docs/checkouts/readthedocs.org/user_builds/jwst-pipeline/conda/latest/lib/python3.6/site-packages (from requests>=2.0.0->sphinx>1.3->sphinx-automodapi)
Requirement already satisfied: idna<2.8,>=2.5 in /home/docs/checkouts/readthedocs.org/user_builds/jwst-pipeline/conda/latest/lib/python3.6/site-packages (from requests>=2.0.0->sphinx>1.3->sphinx-automodapi)
Requirement already satisfied: urllib3<1.24,>=1.21.1 in /home/docs/checkouts/readthedocs.org/user_builds/jwst-pipeline/conda/latest/lib/python3.6/site-packages (from requests>=2.0.0->sphinx>1.3->sphinx-automodapi)
Requirement already satisfied: certifi>=2017.4.17 in /home/docs/checkouts/readthedocs.org/user_builds/jwst-pipeline/conda/latest/lib/python3.6/site-packages (from requests>=2.0.0->sphinx>1.3->sphinx-automodapi)
Requirement already satisfied: pyparsing>=2.0.2 in /home/docs/checkouts/readthedocs.org/user_builds/jwst-pipeline/conda/latest/lib/python3.6/site-packages (from packaging->sphinx>1.3->sphinx-automodapi)
Requirement already satisfied: MarkupSafe>=0.23 in /home/docs/checkouts/readthedocs.org/user_builds/jwst-pipeline/conda/latest/lib/python3.6/site-packages (from Jinja2>=2.3->sphinx>1.3->sphinx-automodapi)
Requirement already satisfied: pytz>=0a in /home/docs/checkouts/readthedocs.org/user_builds/jwst-pipeline/conda/latest/lib/python3.6/site-packages (from babel!=2.0,>=1.3->sphinx>1.3->sphinx-automodapi)
Installing collected packages: sphinx-automodapi, stsci-rtd-theme
Successfully installed sphinx-automodapi-0.7 stsci-rtd-theme-0.0.1
#
# To activate this environment, use:
# > source activate latest
#
# To deactivate an active environment, use:
# > source deactivate
#
```
But currently it barfs at the `sphinx_rtd_theme`.  Hmm.

**Comment by nden** [comment]
This is fixed now. Enjoy the newly built docs with added API info.

**Comment by pllim** [comment]
Ohhh! :clap: 

Just for future reference, what needed to be fixed?

**Comment by nden** [comment]
Nothing special, several dependencies were missing from `.rtd-environment.yml`.

**Comment by jdavies-st** [comment]
Any idea why that started making the docs fail 8 days ago?

**Comment by jdavies-st** [comment]
Right.  That makes sense.  Thanks!
