### ISSUE TITLE
Allow extract_2d in calspec2 for NRC_TSGRISM?

### ISSUE THREAD

**Issue by sosey** [spacetelescope/jwst#2459]
https://github.com/spacetelescope/jwst/blob/af3347fec1b0dc3164d4160e0714f7aa6e358439/jwst/pipeline/calwebb_spec2.py#L230

I just noticed this looking at code in another PR. Since https://github.com/spacetelescope/jwst/pull/2286 allows extract2d for this mode, should we remove this if block? This is probably my oversight to begin with.... @hbushouse

**Comment by hbushouse** [comment]
I think you're right. We are calling `extract_2d` now for NRC_TSGRISM, right? If so, then that line definitely needs to be removed, so that `extract_2d` does get called.

By the way - on a related note - ever since `extract_2d_step` was updated to include the new `grism_objects` argument in the call to `extract_2d`, it's causing all other spectroscopic modes to fail (see the regression tests), because `grism_objects` isn't defined for any of the other modes.

**Comment by sosey** [comment]
shoot, that might have been a merge error on my end...lemme fix both those items and submit an update
