### ISSUE TITLE
dashes in configuration file names

### ISSUE THREAD

**Issue by stscieisenhamer** [spacetelescope/jwst#2557]
# Question

Recently, a number of new calibration configurations were added:

- `calwebb_tso_spec2.cfg`
- `calwebb_tso_spec3.cfg`
- `calwebb_nrslamp_spec2.cfg`

Along with these, new association types were defined. These types appear in the association names. The association names would look like:

- `basename_tso-spec2_asn_001_asn.json`
- `basename_tso-spec3_asn_001_asn.json`
- `basename_nrslamp-spec2_asn_001_asn.json`

Note that in the association names, the types have dashes in them. This is required by the agreed upon standard.

The ground system would like the types to match exactly, making it easier to match/make files, etc. This would require renaming the configuration files with the dashes:

- `calwebb_tso-spec2.cfg`
- `calwebb_tso-spec3.cfg`
- `calwebb_nrslamp-spec2.cfg`

From a consistency standpoint, this would also make better sense for the user.

So, the question is: Is there any issue with using dashes in the configuration file names?

**Comment by sosey** [comment]
+1 for all dashes

**Comment by jdavies-st** [comment]
Now that we've opened the dash floodgates, I see no problem.

**Comment by hbushouse** [comment]
The cfg file names are likely to get typed a lot by users in the future, so having a mixture of underscores and dashes is of course going to be a bit of a pain for them to remember and type each time. But on the other hand, if they're also using the asn files as their input, then it does make sense to have them typeset consistently, because it would be even more confusing if they had to type two different patterns of underscores and dashes. So overall I say go for it.

**Comment by stscieisenhamer** [comment]
# Implementation

- [ ] documentation
- [ ] tests
- [ ] code
- [ ] tests
- [ ] documentation
- [ ] changelog

**Comment by stscieisenhamer** [comment]
Resolved by #2639.
