### ISSUE TITLE
Which version of python should RT be run under?

### ISSUE THREAD

**Issue by jdavies-st** [spacetelescope/jwst#2754]
Our nightly regression tests are currently running `python 3.7`.

What version should they be running?

My thought is that it should be pegged to whatever DMS is using in running our code.  Is this `3.5`?  `3.6`?  If not `3.6`, why not?

It was not actually clear to me from our `JenkinsfileRT` that we were running `3.7`, as the recipe installs Miniconda with `python 3.6.5`, then does a Jenkins build labelled `3.6` with a new conda environment without actually pegging the python version, so it just pulls in the latest `3.7`.  So we need to fix that as a minimum.

Our per-PR CI tests on ssbjenkins and TravisCI are both pegged to `python 3.6`.

Thoughts?

**Comment by jdavies-st** [comment]
@hbushouse @nden @stscicrawford

**Comment by hbushouse** [comment]
I believe that right now 3.6 is the version of choice within DMS. I can check at tomorrow's B7.2 integration tag-up.

**Comment by rendinam** [comment]
Hi @hbushouse , was a decision made on which python version to use? As for releases and deliveries, it might make sense for each to only support a single "official" python version, even if others are used to get a wider sense of behavior during development and testing. Since the python version will be ratcheted up over time, where's a good place to see what _the_ python version is at any given time?

**Comment by jdavies-st** [comment]
Right now this is set to `python 3.6.x`.  Closing.
