### ISSUE TITLE
DOC: Review orphaned RST pages

### ISSUE THREAD

**Issue by pllim** [spacetelescope/jwst#2970]
#2955 had identified a bunch of orphaned documentation pages. Why are they orphaned? Can they be referenced somewhere or should they be deleted altogether?

**Comment by hbushouse** [comment]
It's due to the restructuring of all the JWST reference file docs. There's a standalone xxxx.rst file for each reference file type, but they aren't listed for rendering in any index.rst or other xxxx.rst file. Instead they are rendered by using `include` directives in each of the xxxx.rst files that describe a calibration step (the step doc includes info for whatever ref file is used in the step). They are also included via links in a master reference file doc. See, e.g., https://jwst-pipeline.readthedocs.io/en/latest/jwst/references_general/references_general.html#reference-file-types

**Comment by pllim** [comment]
Okay, if it is not really an issue, then feel free to close.
