### ISSUE TITLE
Failed regression tests should generate an Artifactory upload schema for OKifying

### ISSUE THREAD

**Issue by jdavies-st** [spacetelescope/jwst#2989]
We current generate a `test_*_results.json` that contains commands to upload the failed test results to the `jwst-pipeline-results` repo on our Artifactory server.  Jenkins then uses the Artifactory plugin to automatically push these to our Artifactory server.

Equally (maybe more) useful would be another generated JSON file that would give the upload parameters (file paths really) of updating the truth file with the current test output.  This is simple to implement, and it would make updating the truth files on Artifactory a CLI one-liner
```
jfrog rt u --spec test_foo_update_truth.json
```
for the developer.

The only question is if there should be one JSON file for all the test outputs that fail, or one file for for each failing test output.  I suspect the former would be fine.  If the latter is needed, the JSON file could be easily edited by hand.

**Comment by hbushouse** [comment]
I would instantly think the 2nd option is preferred: a separate json file for each failure. It's almost always the case that different tests get updated at different times for different reasons. Or are you talking about multiple output products from a single test? If so, then I think 1 okifyer file is usually OK, because all of the outputs would normally get updated together.

**Comment by jdavies-st** [comment]
Right, exactly.  One OK-ifier for each test, which in some cases would be a few outputs.

**Comment by jdavies-st** [comment]
Fixed by #4320
