### ISSUE TITLE
test_environmetal is failing, but CI test suite passing

### ISSUE THREAD

**Issue by jdavies-st** [spacetelescope/jwst#3028]
There are two problems here:

1) The test is failing
https://ssbjenkins.stsci.edu/blue/organizations/jenkins/STScI%2Fjwst/detail/PR-3021/2/pipeline/24#step-184-log-349
@stscieisenhamer 

2) The test is failing, but the test suite appears to be passing as 1 failure seems to not be sufficient now for the test run to have failed.  
```
1 failed, 1268 passed, 290 skipped, 18 xfailed, 30 warnings in 1648.25 seconds
```
It looks like the default setup of our CI tools has changed?  @jhunkeler or @rendinam?  Do we need to set one of
```
failedUnstableThresh: 0
failedFailureThresh: 
skippedUnstableThresh: 
skippedFailureThresh:
```
in our `Jenkinsfile` now?

**Comment by jhunkeler** [comment]
1) Test commands transparently execute with `|| true` to avoid a non-zero exit from taking down the entire `Jenkinsfile` pipeline. We know that sucks but we weren't left with much choice.

2) `pytest` emits custom/incorrect `JUnit` XML. `xUnit`, the plugin responsible for ingesting the test results is bombing out because the XML doesn't match the correct schema.

3) https://github.com/pytest-dev/pytest/pull/4511 is/was an attempt to make things work, but I haven't had time to work on it for a while :cry:

**Comment by jdavies-st** [comment]
@jhunkeler, so is this basically fixed now?  I have not noticed this happening anymore on our end.

**Comment by rendinam** [comment]
Yes. #3166 enabled the upstream pytest fix for this.

**Comment by jdavies-st** [comment]
🎉 

Closing this issue.  Thanks @jhunkeler!
