### ISSUE TITLE
Force an ordering of optical components in the Level 3 product naming scheme

### ISSUE THREAD

**Issue by stscieisenhamer** [spacetelescope/jwst#3039]
# Issue
The optical component part of the Level 3 naming scheme enforces no particular order of the elements included. Hence, it is possible that an association, regenerated using the same rules and pool, can produce different product names, where the optical components are in a different order in the name.  There are a couple of issues that arise from this:

- Users can be confused by seeing different names in different reprocessing runs.
- Tests that compare generated associations to "truth" associations are fragile.

Mostly an annoyance, but further discussion is requested.

**Comment by hbushouse** [comment]
Makes sense to me to force the ordering of multiple components of a file name, so that they always come out the same way for repeated runs of the same data. Having them appear differently at random would be confusing to users and software systems. Not sure as to exactly how to enforce the ordering: for instruments having multiple mechanisms (wheels) containing filters, gratings, pupils, etc. perhaps always construct the name using the same order of the mechanism (e.g. filter wheel, then pupil wheel, ...).

**Comment by stscieisenhamer** [comment]
And actually now consider this a true bug. During DP reprocessing, this will allow multiple versions of files to end up in the archive next to each other: Fail 🤕 

Yep, that was how I awoke this morning...thanks brain...no, not during the day...that would be too easy...

**Comment by stscieisenhamer** [comment]
## Implementation
Will use alphabetical ordering.
