### ISSUE TITLE
MBGS: MIRI LRS data

### ISSUE THREAD

**Issue by nden** [spacetelescope/jwst#3150]
Describe MIRI LRS Fixed slit data used in the master background step tests.

**Comment by jemorrison** [comment]
Data created by @hbushouse 
miri_lrs_bkg_rate.fits:  background rate image
miri_lrs_bkg_cal.fits: background cal image (output of calspec2)
miri_lrs_bkg_x1d.fits: background extracted spectrum (output of calspec2 and input to master_background step)
 
miri_lrs_sci_rate.fits: original source+background image (input to calspec2)
miri_lrs_sci_cal.fits: calibrated image from calspec2 (input to master_background step)
 
Notes on miri_lrs_bkg_x1d.fits: Howard  copied  the values from the "NET" column to the "FLUX" column, so that the background spectral data are still in units of countrate.

Comments from @hbushouse "Background data was created with randomized background signal.
I created a bkg rate image, and then ran it all the way through calspec2 to create the bkg x1d file to use as the user-supplied master background. I added that bkg rate image to an existing sci rate image, to form a sci+bkg rate image. That sci+bkg rate image was then run all the way through calspec2 to create the sci+bkg cal image to use as input to the master background step. So they've both been all the way through calspec2.

**Comment by jemorrison** [comment]
Plot of 1-D user spectrum 
![miri_lrs_user_bkg](https://user-images.githubusercontent.com/18491225/53207343-b369f680-35f0-11e9-94a6-f6314101b1f9.png)

**Comment by jemorrison** [comment]
Test 1 :
Input to master background subtraction:miri_lrs_sci+bkg_cal.fits & miri_lrs_bkg_x1d.fits
Run step and then run extract 1-D on the background subtracted result.
Take the original science image with no background add and run extract 1-D on this data.
Compare the two spectra (WHY ARE the Fluxes negative ?)

![lrs_1d_extract_compare](https://user-images.githubusercontent.com/18491225/53208684-e44c2a80-35f4-11e9-9f25-115d64170f63.png)

To better see what is going on subtract these two spectra - the difference spectra should just be ~ noise - and it is!
![lrs_1d_difference](https://user-images.githubusercontent.com/18491225/53208737-19f11380-35f5-11e9-8015-bb20fa5c36cc.png)

**Comment by jemorrison** [comment]
Test 2:
Subtract: background_subtracted result - science for LRS bounding box region
 Mean of this image is 0.185, standard dev 1.616 and max is 5.017 . 
Images are below for reference
Image of Background Subtracted result for LRS region
<img width="340" alt="background_subtracted_lrs" src="https://user-images.githubusercontent.com/18491225/53210079-ca611680-35f9-11e9-8c02-09781a62b080.png">


Image of original science image for LRS region
<img width="338" alt="science_lrs" src="https://user-images.githubusercontent.com/18491225/53210028-a9002a80-35f9-11e9-8d81-1954e4c5761b.png">

Image of difference 
<img width="336" alt="background_subtacted-science_lrs" src="https://user-images.githubusercontent.com/18491225/53210048-ba493700-35f9-11e9-8744-1098ba6f7e3c.png">

**Comment by hbushouse** [comment]
The stdev of the background signal alone (in the miri_lrs_bkg_rate and miri_lrs_bkg_cal files) is ~1.4 and the stdev of the sci data near the spectrum is ~0.2, so combined this seems reasonable compared to the spread in your histogram.

**Comment by hbushouse** [comment]
There's definitely something strange going on in plots 2 and 3 above, that show the middle portions of the spectra flat-lining at almost exactly zero. The data arrays in the miri_lrs_sci_extract1dstep.fits file show this too. Here's a couple data ranges from the 'FLUX' column in that file:
```
In [17]: sx1d[1].data['flux'][130:150]
Out[17]: 
array([ -2.11446478e+00,  -2.68700649e+00,  -2.03216477e+00,
        -2.36835629e+00,  -1.61744019e+00,  -1.87467644e+00,
        -1.64490682e+00,  -2.03428186e+00,  -1.99626471e+00,
        -3.86351254e-04,  -4.03675159e-04,  -4.79877496e-04,
        -3.73976848e-04,  -3.32394006e-04,  -4.53098361e-04,
        -3.91826765e-04,  -3.33440676e-04,  -3.43442465e-04,
        -2.52078996e-04,  -3.56867078e-04])

In [22]: sx1d[1].data['flux'][365:385]
Out[22]: 
array([  1.84023290e-06,   2.49006536e-06,   1.15858468e-06,
         3.63488929e-06,  -3.12037667e-06,  -1.71376898e-06,
        -5.61841770e-06,  -7.34777684e-06,  -1.13736084e-05,
        -1.45430756e+00,  -2.30423717e+00,  -2.30097376e+00,
        -2.68228305e+00,  -2.70696885e+00,  -2.91978207e+00,
        -3.38021958e+00,  -2.98587678e+00,  -2.94749940e+00,
        -3.14925293e+00,  -3.04770429e+00])
```
Notice how the data on the ends are on the order of a few DN/s per pixel, while in the middle they suddenly jump to e-5 or e-6. I suspect that the presence of the RELSENS extension in the _cal file is causing the `extract_`1d` step to apply the flux cal, which is defined over a limited wavelength range. The 'NET' column doesn't show this behavior. 

I'm going to reprocess the science cal data to make sure nothing is being done with flux calibration at any step of the pipeline.

**Comment by jemorrison** [comment]
Something is not right at all with the NRS-MOS data. Send me the script or steps you use to reprocess the LRS data and I will run it on the NRS-MOS. It does not make sense to me the flux calibration are the 1 for NIRSPEC but I will try reprocessing to see if that solves the problem.

**Comment by hbushouse** [comment]
OK, I have the LRS figured out and everything seems to be fine. There are 2 things that were causing confusion (at least for me).

1) The RELSENS data only go from 4.97 - 12.01 microns, while the wavelength range of the pixels within the bounding box goes from 3.57 - 14.37 microns, so there are pixels/bins on both ends of the spectrum that don't get calibrated, but they also aren't zeroed out (they're left in their native units). So that's what causes the jumps, with the middle portion of all the comparisons being nearly zero. I modified a copy of the jwst_miri_photom ref file to extend the wavelength of the end points to cover all the data, after which everything is nice and smooth and continuous.

2) Even after fixing the flux calibration issue, I was getting comparisons that just looked way too good. Differences between the original sci spectrum (without any background) and the sci+bkg after running through master_background were just too close to absolute zero to be believable (I thought), because the artificial background signal has noise in it. But then I realized that the wavelength values in the miri_lrs_bkg_x1d.fits file (used as master background spectrum) match exactly the wavelengths of the pixels in the miri_lrs_sci+bkg_cal.fits file (used as input to master_background step), so the `expand_to_2d` and `np.interp` functions used to create the 2-D background really aren't doing any interpolating. We're giving it wavelengths that are nearly an exact match to the background spectrum. So it replicates exactly the sum (over the extract_1d aperture size) of the artificial background at each wavelength value, so that the master-background-subtracted x1d data are an exact match to the original. I confirmed this by introducing a slight shift in the wavelength values in the miri_lrs_bkg_x1d.fits file used as input to `master_background` and then - voila! - when I take the difference of the background-subtracted x1d to the original x1d I get a spectrum that still has near zero mean, but it's now got some non-zero dispersion to it, due to the dispersion (noise) from wavelength to wavelength bin in the miri_lrs_bkg_x1d.fits file.

I'll attempt to attach plots below.

**Comment by hbushouse** [comment]
Here's the original miri_lrs_sci_x1d.fits spectrum plotted vs. the sci+bkg after run through master background subtraction. The original is the one with very little noise that runs through the middle (mean) of the noisier round-trip spectrum. The round-trip is noisy because I shifted the wavelength values a little, causing np.interp to actually do some interpolating.

![figure_sci_bsub](https://user-images.githubusercontent.com/12860084/53268856-35235800-36b5-11e9-8acd-3ed8172867c7.png)

**Comment by hbushouse** [comment]
Now here's the difference of the original and round-trip spectra. The mean is a flat-line at zero, with noise.
![figure_diff](https://user-images.githubusercontent.com/12860084/53268892-5a17cb00-36b5-11e9-9e20-5be249ae0fbf.png)

**Comment by hbushouse** [comment]
So now that I've convinced myself that the near-zero differences seen in normal processing, i.e. when the wavelengths in the user-supplied spectrum are a match to the wavelengths in the science data, such that no interpolation happens, I've rerun all the example files using the normal processing. The flow of processing is:

- add a small DC (constant) offset to the SCI array of miri_lrs_sci_rate.fits to prevent issues with negative count rates that just confuses the comparisons
- copy miri_lrs_sci_rate.fits to miri_lrs_bkg_rate.fits, to use as a template bkg file
- replace the entire SCI array in miri_lrs_bkg_rate.fits with output of np.random.poisson()
- copy miri_lrs_sci_rate.fits to miri_lrs_sci+bkg_rate.fits and add miri_lrs_bkg_rate.fits SCI array to the miri_lrs_sci+bkg_rate.fits SCI array, to add the random bkg signal
- strun calwebb_spec2.cfg miri_lrs_sci_rate.fits to produce cal and x1d products for later comparison
- strun calwebb_spec2.cfg miri_lrs_sci+bkg_rate.fits to produce cal product for use as input to master_background step
- strun calwebb_spec2.cfg miri_lrs_bkg_rate.fits --steps.photom.skip=true to produce bkg x1d spectrum
- edit miri_lrs_bkg_x1d.fits to copy 'NET' values to 'FLUX' column
- strun jwst.master_background.MasterBackgroundStep miri_lrs_sci+bkg_cal.fits --user_background=miri_lrs_bkg_x1d.fits (produces miri_lrs_sci+bkg_masterbackgroundstep.fits)
- strun jwst.extract_1d.Extract1dStep miri_lrs_sci+bkg_masterbackground.fits (produces miri_lrs_sci+bkg_extract1dstep.fits)

**Comment by hbushouse** [comment]
The following plot is an overplot of the original miri_lrs_sci_x1d.fits spectrum (without bkg added) and the master_background-subtracted version miri_lrs_sci+bkg_extract1dstep.fits, where only the region of the data arrays that have flux-cal values in the RELSENS extension are included. The two lay directly on top of another, so you really only see one of them.

![figure_new_sci_bsub](https://user-images.githubusercontent.com/12860084/53360287-2500b800-3903-11e9-82be-c4b8c470fbda.png)

**Comment by hbushouse** [comment]
This one shows the difference of the original and master_background-subtracted spectra, again only plotting the values that have flux-cal applied to them. The mean difference is essentially zero, with noise.
![figure_newdiff](https://user-images.githubusercontent.com/12860084/53360343-4e214880-3903-11e9-8c5e-3331464e76ec.png)

**Comment by hbushouse** [comment]
All of the example files /grp/jwst/ssb/chartreuse/master_background_data/miri-lrs/ have now been updated with these latest results.
