### ISSUE TITLE
MBGS: NRS FS data

### ISSUE THREAD

**Issue by nden** [spacetelescope/jwst#3151]
Describe Nirspec Fixed Slit data used in the master background step tests.

**Comment by jemorrison** [comment]
The data is found at: /grp/jwst/ssb/chartreuse/master_background_data/nrs-fs

@nden created the data
nrs1_bkg.fits: 2D background rate image.
nrs1_bkg_cal.fits: background cal image (output of calspec2) 
nrs1_bkg_x1d.fits: background extracted spectrum (output of calspec2 with photom step turn off. This data has 4 EXTRACT1D extensions. The FLUX column=0, NET is used in master_background. 
nrs1_bkg_x1d_user.fits:  Contains only 1 extracted spectrum from nrs1_bkg_x1d.fits- the first one (created by @jemorrison). Input to master_background step, using NET column. 
nrs1_sci.fits : input science rate image
nrs1_sci_cal.fits: science cal image (output from clasped 2). Used for testing
nrs1_sci_bkg.fits: science image + background rate image 
nrs1_sci_bkg_cal.fits: science image and background cal image (output from CalSpec2). Input to master background step.

Notes on the process both the background, science and science +background data was run all the way  through calspec2. For the background data the photom step was turned off so that the extract-1d step would not apply the flux calibration.

**Comment by jemorrison** [comment]
1-D user background spectrum
![nirspec_fs_user_bkg](https://user-images.githubusercontent.com/18491225/53197651-d805a480-35d7-11e9-9f61-e0793b60678d.png)

**Comment by jemorrison** [comment]
Here are the results I have so far for the FS. The first slit looks good. _But is there as a way to (a flag) to tell if a pixel belongs to a slit even if it is in the bounding box._ If I understand the bounding box it is a rectangular-ish  region, but since the slits are curved in this region there are pixels that do not really fall on the slit but are in the bounding box. So I would rather not use these pixels in statistics of how well the test is working. For the IFU data the invalid pixels in a slit have ra, dec values of NaNs. I_s this how I should check all pixels if they are valid in a fixed slit ?_
For Slit 1 here is the 1-D extracted spectra for result from step and original science.
![compare_1d_1](https://user-images.githubusercontent.com/18491225/53301674-fb686380-3812-11e9-8734-78ff01a39e58.png)

Subtracting these two 1-D spectra - looks good except for the edge of the slit which I would like to remove from statistical tests that I could put in the regression test. 

The images for the for this silt:
![compare_images_nirspec_fs_slit1](https://user-images.githubusercontent.com/18491225/53301701-51d5a200-3813-11e9-8392-dc7c61d39f66.png)

![diff_nirspec_fs_1d_1](https://user-images.githubusercontent.com/18491225/53301681-218e0380-3813-11e9-9c93-bdb247be3859.png)

It almost seems like the bounding box is not right for this slit - too large ? The white region in the top image  is because in the sci+bkg and result from the step the pixels values are the same - so I guess the there is no real data in the slit ? The pixel values in the original science image are about 300 counts lower (which I am guessing is because the added background put in is around 300 counts).

Here are the results for slit 2
Comparison of 1-D extracted spectra for result from step and original data
![compare_1d_2](https://user-images.githubusercontent.com/18491225/53301806-8138de80-3814-11e9-9374-6516b2f25b7c.png)
 Difference of two spectra 
![diff_nirspec_fs_1d_2](https://user-images.githubusercontent.com/18491225/53301823-a4638e00-3814-11e9-9374-6325c31f94be.png)
 The spike in the middle is I think caused by some hot pixels original science image. For the statistical check I am first performing a 5 sigma clip on the data and comparing the remaining data. 
The images for this slit:
![compare_images_nirspec_fs_slit2](https://user-images.githubusercontent.com/18491225/53301845-d07f0f00-3814-11e9-9d22-564d79e723ae.png)

So the third and fourth slits have a larger difference in the 1-D extracted spectra that I do not understand yet. It seems the user 1-D background subtracted too much for slit 3 and too much too little for slit 4 ? **This could be the way I created the User 1-D background to use in the step. I took the first slit in the multi spec background as the 1-D User. Could this somehow mess up slits 3 and 4. ?**

When I compare the result from the step - original the pixel values are negative.
![compare_1d_3](https://user-images.githubusercontent.com/18491225/53301860-0623f800-3815-11e9-933a-1965d8725029.png)

![diff_nirspec_fs_1d_3](https://user-images.githubusercontent.com/18491225/53301862-0f14c980-3815-11e9-82e1-f0f4f16bbbf8.png
![compare_images_nirspec_fs_slit3](https://user-images.githubusercontent.com/18491225/53301931-c90c3580-3815-11e9-9189-f1fecf07273f.png)

Slit 4 - not quite right. Some pixels seem to have too much background subtracted while other too little.

![compare_nirspec_fs_1d_4](https://user-images.githubusercontent.com/18491225/53301933-d45f6100-3815-11e9-945a-5d2ffc9a4978.png)
![diff_nirspec_fs_1d_4](https://user-images.githubusercontent.com/18491225/53301935-d9bcab80-3815-11e9-8737-374ba9496055.png)
![compare_images_nirspec_fs_slit4](https://user-images.githubusercontent.com/18491225/53302003-df66c100-3816-11e9-91fe-d50e6f6eda66.png)

**Comment by jdavies-st** [comment]
> Here are the results I have so far for the FS. The first slit looks good. _But is there as a way to (a flag) to tell if a pixel belongs to a slit even if it is in the bounding box._ If I understand the bounding box it is a rectangular-ish region, but since the slits are curved in this region there are pixels that do not really fall on the slit but are in the bounding box. So I would rather not use these pixels in statistics of how well the test is working. For the IFU data the invalid pixels in a slit have ra, dec values of NaNs. I_s this how I should check all pixels if they are valid in a fixed slit ?_

NIRSpec FS works the same as NIRSpec MSA and NIRSpec IFU.  The ra/dec/lambda are are NaNs for pixels were the WCS is not defined, i.e. were light from the sky did not go through the slit and fall on the detector.

**Comment by jdavies-st** [comment]
> This could be the way I created the User 1-D background to use in the step. I took the first slit in the multi spec background as the 1-D User. Could this somehow mess up slits 3 and 4?

The slits have different slit heights and widths, so yes, possibly.  It looks like `photom` step has been turned off for the extracted 1D spectra?

**Comment by philhodge** [comment]
If the wavelengths in the 1-D background array do not cover the entire range of wavelengths in the 2-D (MultiSlit) science data array, the background values in the output of expand_to_2d will be set to zero for pixels whose wavelengths are outside the range of the 1-D background array.  So yes, you can see a discrepancy near the ends in this case.

**Comment by jemorrison** [comment]
So in this test case I use the extracted 1-D for the first slit as the user background 1-D.
In plot 2 (Difference from 1-D extracted spectra from step and 1-D extracted spectra from original science file)  for slit 1 - this data should all be consistent. User 1-D covers exactly the same wavelengths as the slit. The values for the low wavelengths for the 1-D extracted are about 2000 DN/S different. 1-D extracted from output of step: ~64570 and original science file ~62568. 

So I still do not understand the large differences at the edge of slit. Maybe it is related to how the
background was added.

**Comment by jemorrison** [comment]
Ha I remembered why I used the first slit as the background. There are some spikes in 1-D spectra for the background for the other slits. Below is the 1-D spectra for the second slit. I was going to use this as the user input. But I need to "clean it first". I have a little routine that loops over the spectrum
and finds large jumps by looking at adjacent values. I was just going to take the average of near by points that did not have a jump. It is a bit of work because there are sometimes a few adjacent values that are "jumps".  Does this fix make sense - or should I do something else.  What if I just removed those points from the spectrum - would that cause any problems down the line. 
So if there are 1465 values in the 1-D spectrum and there are 3 spikes the user 1-D spectrum would
have 1462 values. 
![nirspec_fs_user_bkg](https://user-images.githubusercontent.com/18491225/53369018-6e530680-3907-11e9-9c0d-8feb3614b465.png)

**Comment by philhodge** [comment]
I like the idea of interpolating better than just deleting the points.  It's probably better for the change in wavelength to vary smoothly from one pixel to the next.

**Comment by jemorrison** [comment]
ok - will do.

**Comment by jemorrison** [comment]
Ok I realized  that the user created background 1-D extracted spectrum did not cover the same wavelength ranges as the 1-D extracted of the science data because there must of been changes to
to extract1D from when that background 1-D spectrum was and now. So I tested this an re-ran
just extract1D on nrs1_bkg_cal.fits - **that is all I needed to do right ? I did not need to re-run spec2 on
the rate file did I ?**

Now both the input user 1-D spectrum and output 1-D extracted spectra have non-zero flux values for the same wavelength range. I picked the 1-D extracted user spectrum to be the fro the second slit since it covers the widest wavelengths. The subtraction of the extracted1-D spectra from the masterbackground step and the science  for the first slit now do not have the edge differences. I wonder if the difference is too large: +/- 100
![diff_nirspec_fs_1d_1](https://user-images.githubusercontent.com/18491225/53449987-61eaae80-39d8-11e9-8cbe-23573243b6ac.png)

For the third slit I do not really understand this difference. It seems too high and has a shape.
The same is true for the 4th slit. The second slit has some spikes that I need to remove before I can figure out how well it is work.
Difference in 1-D spectra for slit 3
![diff_nirspec_fs_1d_3](https://user-images.githubusercontent.com/18491225/53450182-d3c2f800-39d8-11e9-86aa-62a9535c5289.png)


Difference in 1-D spectra for slit 4
![diff_nirspec_fs_1d_4](https://user-images.githubusercontent.com/18491225/53450215-dcb3c980-39d8-11e9-8f44-2d022e4db1a8.png)

**Comment by hbushouse** [comment]
I've just finished reprocessing and reanalyzing the FS data and everything looks good now. As with the MOS mode, the flat-fielding adds complications, such as modulating the constant bkg signal, so I reprocessed everything from scratch through `calwebb_spec2` with `flat_field`, `pathloss`, and `resample_spec` turned off. It's OK to leave `photom` turned on, because the NIRSpec ref files are filled with 1's right now, and that way you end up with the "FLUX" column of the x1d tables already populated, with the same values as the "NET" column (so you don't have to do any copying).

The image with the artificial bkg signal injected ("nrs_bkg_rate.fits") covers all 4 slits present on the NRS1 detector, so "nrs_bkg_x1d.fits" has 4 extracted spectra in it. I chose to use the data from Slit 2 for the user background, because it has a large wavelength range. I created a new "nrs_bkg_user_x1d.fits" file that contains only the Slit 2 data, so that the `master_background` step doesn't complain about multiple spectra in the user-supplied file.

Here's the run-down of files that are now in the standard directory:
`nrs_bkg_rate.fits`: The full-frame image with artificial bkg signal in the bounding_box regions of the 4 slits
`nrs_bkg_cal.fits`: The output of `calwebb_spec2`
`nrs_bkg_x1d.fits`: The other output of `calwebb_spec2`, with data for all 4 slits
`nrs_bkg_user_x1d.fits`: The slit 2 1-d spectrum, for use as input to `master_background`
`nrs_sci_rate.fits`: Original full-frame science image, with no background added
`nrs_sci_cal.fits`: Output of `calwebb_spec2`
`nrs_sci_x1d.fits`: Output of `calwebb_spec2`
`nrs_sci+bkg_rate.fits`: Full-frame image with science+background signal
`nrs_sci+bkg_cal.fits`: Output of `calwebb_spec2`, input to `master_background`
`nrs_sci+bkg_x1d.fits`: Output of `calwebb_spec2`
`nrs_sci+bkg_masterbackgroundstep.fits`: Output of `master_background`; 2-d cutouts with bkg subtracted for all 4 slits
`nrs_sci+bkg_extract1dstep.fits`: Output of `extract_1d`; 1-d background-subtracted spectra for all 4 slits

**Comment by hbushouse** [comment]
Now here are results. The following plots show the 2-d cutouts for each slit, showing the original Sci  image (no background), the background-subtracted image, and the difference of those two.
![slit1_2d](https://user-images.githubusercontent.com/12860084/53600963-ef650480-3b78-11e9-959e-d6acc7d3d6bc.png)
![slit2_2d](https://user-images.githubusercontent.com/12860084/53600971-f55ae580-3b78-11e9-94fa-59034e9ac42d.png)
![slit3_2d](https://user-images.githubusercontent.com/12860084/53600975-fa1f9980-3b78-11e9-884f-f24270d4586e.png)
![slit4_2d](https://user-images.githubusercontent.com/12860084/53600981-fdb32080-3b78-11e9-9700-d3f17a3c3a05.png)

**Comment by hbushouse** [comment]
As you can see, the difference images for each slit are nuthin' but net ... err, noise. It's not easy to see in these images, but the residual noise level for slit 2 is much smaller than the others, because it was the slit 2 bkg spectrum that was used as the user-supplied input to `master_background`, so there's a much closer match to the imposed bkg signal.

**Comment by hbushouse** [comment]
It's easier to see the results by differencing the 1-d spectra for each slit. The following plots show the differences of the spectra from `nrs_sci_x1d.fits` (the original data with no bkg) and `nrs_sci+bkg_extract1dstep.fits` (background subtracted) for each slit. Here's it's easy to see how much lower the residual noise is for Slit 2. Sorry about the poor plotting that resulted in overlaps ...
![allslits_1d](https://user-images.githubusercontent.com/12860084/53601256-aa8d9d80-3b79-11e9-96a6-52b6a43edab5.png)

**Comment by hbushouse** [comment]
So I'd say this indicates success!

**Comment by jemorrison** [comment]
By the way did you plot the 1-D spectrum you used for the user provided one. When I used the
old data there were a few spikes in the data that I thought would cause problems with the background
subtraction step so I replaced the spikes with an interpolated values of near by wavelengths.

**Comment by hbushouse** [comment]
Matthew 7:7
![bkg_1d](https://user-images.githubusercontent.com/12860084/53601826-0147a700-3b7b-11e9-8ceb-94552cf4817e.png)
Only the very first element is an outlier.

**Comment by jemorrison** [comment]
The NIRSpec FS results for comparing the 1-D spectra for Slit 1,3,4 have a larger difference
than the NIRSpec MOS data. The typical mean (1- D spectrum Master BKG - Science) for the 
NIRSPec Mos data was less than 0.7 and the plot looks more like the NIRSpec Slit 2 results. The rest of the FS results 1,3,4 as shown by Howards plot above (2 above) are much noiser.  They have a mean for subtracted 1-D spectrum of close to 3.
Not sure why that is. But for now I am going to set the tolerance for the mean of FS subtract 1-D spectra to be 3 in the regression test.
