### ISSUE TITLE
Fringe step should use DQ arrays

### ISSUE THREAD

**Issue by dmggh** [spacetelescope/jwst#3937]
The step relies on np.isfinite() of the science data to determine which pixels should have the correction applied, but instead should use the DQ values.

**Comment by hbushouse** [comment]
@jemorrison Is this still an issue? I don't see any use of np.isfinite() in the fringe code, but it does use np.isnan(). It also doesn't make any use of DQ flags at all.

**Comment by nden** [comment]
@jemorrison Please review and close if not relevant.

**Comment by jemorrison** [comment]
@drlaw1558 @hbushouse 
The residual_fringe code does not use the dq values but instead looks where the rate data is a NAN. Since bad pixels should have nan values this should be the same thing.  Searching and not using pixels flagged with DO_NOT_USE flag is the standard way our pipeline works, but making that change should not affect this code. We could have another check that searches for bad pixels sets the values to NaN - which would be the easiest thing and the safest thing for this code.
The  main reason I could see doing this is just maintenance down the line since using the DQ mask is the standard way the pipeline works. 
@hbushouse what do you think. I would just add one line above 
 nanval_indx = np.where(~np.isfinite(output_data)
The would search the output_data (copy of input data) and set values with DQ=DO_NOT_USE to nan.
Is this sort of check any place in the cal detector 1 pipeline ?
If it is I would not bother adding this the code and I will close this ticket.

**Comment by drlaw1558** [comment]
I think the idea was that eliminating everything with DQ flag of DO_NOT_USE could still potentially miss any non-finite values that had snuck into the SCI array and cause a crash, so the code simply throws out non-finite SCI values.  Really, it should throw out *both* DO_NOT_USE values in the DQ array and non-finite values in the SCI array.  In an ideal world those would be identically the same pixels, but isn't necessarily the case.

**Comment by hbushouse** [comment]
I agree that it seems like we should be consistent across steps and hence this step should throw out pixels that are NaN in the science array **and** pixels flagged as DO_NOT_USE in the DQ array. You never know when one condition might exist without the other (despite the fact that they shouldn't).

**Comment by jemorrison** [comment]
This is still relevant and should be added to list of issues to get into the next build

**Comment by hbushouse** [comment]
OK, thanks Jane. I'll add it to the B10.0 milestone.

**Comment by hbushouse** [comment]
@stscijgbot-jp

**Comment by stscijgbot-jp** [comment]
_This issue is tracked on JIRA as [JP-3288](https://jira.stsci.edu/browse/JP-3288)._

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-3288?focusedCommentId=693468#comment-693468):_

Fixed by #8381

**Comment by stscijgbot-jp** [comment]
_Comment by [David Law](https://jira.stsci.edu/secure/ViewProfile.jspa?name=dlaw) on [JIRA](https://jira.stsci.edu/browse/JP-3288?focusedCommentId=696458#comment-696458):_

LG2M, closing.
