### ISSUE TITLE
Question on intended use of install_requires in setup.py

### ISSUE THREAD

**Issue by rendinam** [spacetelescope/jwst#3988]
An approach being validated to provide environment deliveries to DMS generates an environment dump at the conclusion of each successful regression testing run. The nightly regression testing job performs a `pip install -e .[test,ephem]` for the 'stable-deps' build configuration (as seen in `JeninsfileRT`). This obtains dependencies as per the `install_requires` list in `setup.py`. However, currently there are three non-stable/unreleased dependencies in that list:

`astropy @ git+https://github.com/astropy/astropy@5f7c192#egg=astropy`
`gwcs @ git+https://github.com/spacetelescope/gwcs@3e2bc108e#egg=gwcs`
`photutils @ git+https://github.com/astropy/photutils@99f101be#egg=photutils`

The development snapshot dependencies above are problematic for this approach as they cannot be obtained from PyPI when the environment is to be recreated elsewhere, due to their not corresponding to released packages.

I notice there is a `requirements-dev.txt` file that seems to be intended to accommodate development snapshot dependencies, and a JWST-UNSTABLE Jenkins job that might be a more appropriate place to use the unreleased dependencies noted above.

Is it possible to designate the `stable-deps` build configuration and the `install_requires` list in `setup.py` to be used only for stable dependency sets, and by extension, only include stable dependencies in the `install_requires` list of `setup.py`?

attn: @jdavies-st, @nden

**Comment by jdavies-st** [comment]
> Is it possible to designate the `stable-deps` build configuration and the `install_requires` list in `setup.py` to be used only for stable dependency sets, and by extension, only include stable dependencies in the `install_requires` list of `setup.py`?

Unfortunately not. For the past month now we've been depending on dev releases of `astropy`, `gwcs` and `photutils` for our package, as we've been developing those packages in parallel.  It will be like this for a while, and probably for our next release to DMS.  Didn't quite think through the ramifications of `pip freeze` output pointing to a non-existent dev version instead of the github commit hash.

We do use `requirements-dev.txt`, but that's to test `jwst` against the latest master of the listed packages, not necessarily the specific hashes we currently depend on.

It's possible we could make a `requirements.txt` that had the specific dev hashes of those 3 packages that we currently depend on.  And install via `pip install -r requirements .[test,ephem]` in our `stable-deps` build config.  Would that be a way forward?

**Comment by rendinam** [comment]
Yes, adding a `requirements.txt`-formatted file with whatever development versions of dependencies are required should be a sustainable way to accommodate those types of dependencies and also allow for the automatic creation of YML environment snapshots.

**Comment by rendinam** [comment]
In order to avoid splitting the dependency list across two locations, perhaps moving all the dependency definitions into `requirements.txt` would be an option.

The only requirement to allow the nightly testing job to compose an environment snapshot is to be able to directly access the raw dependency information, including any such development dependencies of the form, e.g. `gwcs @ git+https://github.com/spacetelescope/gwcs@3e2bc108e#egg=gwcs`. Released dependency names are obtained accurately by the environment dumping process and can be defined anywhere. If all dependencies are stored in a `requirements.txt` file, the above requirement is met and this also removes the need for diligence in keeping track of which dependencies go where, which seems less error prone, but either approach should work.

**Comment by rendinam** [comment]
Putting the dependencies in `setup.cfg` might be another way to proceed as well without having to create and manage another file.

**Comment by jdavies-st** [comment]
Dependencies can either be in `setup.cfg` or `setup.py`, but these need to be our minimal dependencies with the broadest range of versions.

DMS on the other hand needs a `requirements.txt` file that not only pins all those dependencies to specific version, but also pins the dependencies of those dependencies.  I.e. a snapshot of the environment that one would get with `pip freeze`, but with `gwcs @ git+https://github...` instead of `gwcs==0.12.dev22`.

Would it be enough to maintain this requirements file and pass it along to SDP?  Or would it be better to turn it into a YAML file as produced from `conda env dump`, but replacing as above those packages installed from github?
