### ISSUE TITLE
Incorrect meta.instrument.detector in combined i2d products

### ISSUE THREAD

**Issue by larrybradley** [spacetelescope/jwst#4681]
The `resample` step can combine multiple detectors (this will be typical for NIRCam), thus the `meta.instrument.detector` value should be set to `None` (according to @jdavies-st).

The `jw42424-o002_t001_nircam_clear-f444w_i2d.fits` file produced by the `test_nircam_image.py` regression test is the combination of both NIRCam LW detectors.  However, its `meta.instrument.detector` is incorrectly set to `NRCALONG` instead of `None`.

**Comment by jdavies-st** [comment]
And to clarify, once the two LONG detectors are combined into a single output resampled file, the keyword `detector` no longer applies.

At this point, CHANNEL should be used, i.e. SHORT vs LONG.

**Comment by jdavies-st** [comment]
This probably means that `model_blender` needs a rule that specifies removing a keyword if it no longer applies to the output data.

**Comment by hbushouse** [comment]
Currently the `core.schema.yaml` file, which defines `instrument.detector` and associated FITS keyword `DETECTOR`, only has the specification:
```
blend_table: True
```
which means that `model_blender` will simply include this keyword in the HDRTAB extension, so that the values from all input exposures get recorded, but the value used in the header of the combined product will correspond to whatever data model was used to make the initial version of the product's primary header.

This keyword should probably have the additional specification:
```
blend_rule: multi
```
which will set the keyword value to "MULTIPLE" if there are multiple values in the input list or set it to the common value if the inputs all have the same value. This would also require the addition of the value "MULTIPLE" to the enum list for the `DETECTOR` keyword in `core.schema`.

**Comment by stscijgbot-jp** [comment]
_This issue is tracked on JIRA as [JP-1410](https://jira.stsci.edu/browse/JP-1410)._
