### ISSUE TITLE
Add tag latest for reliable install of the latest version automatically

### ISSUE THREAD

**Issue by ccossou** [spacetelescope/jwst#5098]
Hello, 

This is just a request that might prove to be stupid. 

I'm writing installation procedures for the commissioning analysis for MIRI, We base our dependencies on the pipeline. Right now it is not possible to install the latest version of the pipeline automatically (to my knowledge).

One has to know the version number to install the pipeline. 

Instead of using 
```bash
pip install git+https://github.com/spacetelescope/jwst@0.16.2
```
I'd like to use:
```bash
pip install git+https://github.com/spacetelescope/jwst@latest
```
or any other way to install automatically the latest stable version of the pipeline. 

Does that seem like a sensible request to you? Do you know any way to do why I'd like already? Without any tags, pip will install the latest commit that will not necessarily be stable.

**Comment by jdavies-st** [comment]
Not stupid at all!  Somehow the refactor of our README install procedures omitted the fact that we have a `stable` branch that points to the latest release.  It can be installed like the following:

```
pip install git+https://github.com/spacetelescope/jwst@stable
```

I will update our README to point this out.

I also think that we should start delivering our releases to PyPi so that they can be easily installed via

```
pip install jwst
```

What say you @hbushouse?

I think a lot of other packages such as `mirage`, `jwql` and the rest of the MIRI JWST python ecosystem would be very happy about this too, as they could then properly list `jwst` in the `install_requires` items in setup.py, and vastly simplify installation of their own packages.  Thoughts @bhilbert4 and @bourque?

**Comment by ccossou** [comment]
This is exactly what I was looking for. Of course, PyPi would be even better but as far as I'm concerned, this issue can be considered closed. I let you handle the closure at your convenience in case you want to track the PyPi request here. 

Thanks for the quick answer !

**Comment by bourque** [comment]
@jdavies-st @hbushouse Yes please!  It would make it a lot easier for us on `jwql` if we could simply `pip install jwst`.

**Comment by hbushouse** [comment]
We had been waiting to make the package available from PyPi till we had our first official public release (i.e. version 1.0), but given that it's already publicly available via github, I guess also having it in PyPi doesn't really make much difference. So ... go for it.

**Comment by jdavies-st** [comment]
Just leaving a comment here that `jwst` can now easily be installed via

```
pip install jwst
```

starting with version 0.17.0.  This will be the way to install from here onward.  And packages like `jwql` and any others that depend on the `jwst` package can now list it in `install_requires` in setup.
