### ISSUE TITLE
NIRCam WFSS extraction boxes shift from the object center 

### ISSUE THREAD

**Issue by kashinod** [spacetelescope/jwst#6219]
NIRCam WFSS extraction boxes shift by more than 1" along the direction vertical to the spectra.  I am processing mosaicked NIRCam grism images, which are generated with mirage.  Note that the observations use only Grism R and now adopt PA=0, so the shift is along the declination axis.  The offsets don't show significant variations across the field that consists of four visits.

The source catalog obtained from calwebb_image3 (the source positions and SKY_BBOX_xx values) looks fine.

The offsets are already seen in the uncal.fits (linear.fits), created by mirage, and rate.fits images (after calwebb_detector1); the declination values of the pixels on which a spectrum falls shift from the source's declination.  Thus, it is perhapse related to the wcs assignment in mirage.

The software versions are jwst-1.2.3 and mirage-2.1.0, and the same problem happened with older versions.
Although others have already submitted similar issues, I would appreciate some more help/information.
[NIRCam_WFSS_extraction_box_shift.pdf](https://github.com/spacetelescope/jwst/files/6822494/NIRCam_WFSS_extraction_box_shift.pdf)

**Comment by hbushouse** [comment]
@stscijgbot-jp

**Comment by stscijgbot-jp** [comment]
_This issue is tracked on JIRA as [JP-2202](https://jira.stsci.edu/browse/JP-2202)._

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2202?focusedCommentId=538962#comment-538962):_

The WCS that exists in uncal and rate products is very minimal and doesn't include any information that includes distortions or anything to do with spectral dispersion. At best it contains only pointing information for the aperture reference point, so it's not obvious to me how accurate or trustworthy any computed RA/Dec source positions would be in those products. It's not until the assign_wcs step in calwebb_spec2 is applied that there is a full, accurate WCS object for the image, from which more accurate RA/Dec values can be obtained.

**Comment by jdavies-st** [comment]
Hi Daichi, from the PDF it looks like the _cal.fits products of the grism images (i.e. the result of `calwebb_spec2`) have bounding boxes that are offset from what they should be?  Is that the problem?  And this happens using the standard workflow of NIRCam WFSS data through the pipeline?

To reiterate the standard workflow:

 - run the direct images through levels 1, 2 and 3 to produce a source catalog _cat.fits from the resampled mosaic _i2d.fits, and then
 - run the dispersed images through level 1 and 2, using the above source catalog `calwebb_spec2`?

And the end result of `calwebb_spec2` is the _cal.fits files with a SCI extension for each source cutout.  And these show the offset?

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2202?focusedCommentId=539114#comment-539114):_

While working on the wfss_contam step, which also used simulated NIRCam direct and grism images produced with Mirage, I found that Mirage is using a newer set of NIRCam grism dispersion/trace coefficients than what's in the relatively old "specwcs" reference files in CRDS. So this results in a mismatch between the dispersed locations of grism spectra in the Mirage images and their computed/predicted locations that the cal pipeline computes based on the specwcs coefficients, and one of the major differences was noticeable offset in the cross-dispersion direction of the spectra. I was able to account for this by taking [Norbert Pirzkal](https://jira.stsci.edu/secure/ViewProfile.jspa?name=npirzkal)'s latest set of NIRCam grism trace/dispersion coeffs (used in Mirage) and putting them into a new set of "specwcs" ref files for CRDS. When I use those updated specwcs ref files in the cal pipeline the offsets go away. So the displacements you're seeing may have similar origin.

Unfortunately we haven't yet been able to install those updated specwcs ref files into CRDS, because it's been discovered that something has changed in the models that Nor uses for those coefficients, which result in the transforms not being able to round-trip properly. We need to work out that problem before we install the updated specwcs ref files into CRDS. I could make my local copies of them available to you, if desired, to see if they make a difference in the results you're getting. They need to be used when running the grism images through the assign_wcs step in the calwebb_spec2 pipeline.

**Comment by kashinod** [comment]
Thank you for the detailed information, and I'm glad to hear that you found a temporal solution of this problem.  I would appreciate it if you could share your files with us. 

@jdavies-st Sorry for the late reply.  Yes, that is exactly what we have done.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2202?focusedCommentId=539457#comment-539457):_

The attached PDF showing examples indicates that your simulations were done with the F356W filter and GrismR. I don't know which instrument module you used (A or B), so I'm attaching the updated specwcs ref files for both modules (NIRCAM_F356W_modA_R.asdf and NIRCAM_F356W_modB_R.asdf). These need to be used in the assign_wcs step when running the calwebb_spec2 pipeline on the grism images, e.g.

strun calwebb_spec2 <your_grism_spec2_asn_file> --steps.assign_wcs.override_specwcs=NIRCam_F356W_modA_R.asdf

That should hopefully result in WCS transforms that give a better matchup to the object positions.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2202?focusedCommentId=539459#comment-539459):_

 [^NIRCAM_F356W_modB_R.asdf]  [^NIRCAM_F356W_modA_R.asdf]

**Comment by kashinod** [comment]
Thanks, but I did not find how to get the attached asdf files (yes, I'm using both modules A and B).

**Comment by hbushouse** [comment]
@kashinod The ASDF files were attached to the Jira ticket that corresponds to this github issue, so you may have not had access to them. But glad to hear that you got it working. Let us know if the new results look correct and, if so, we can close this issue.

**Comment by stscijgbot-jp** [comment]
_This issue is tracked on JIRA as [JP-2202](https://jira.stsci.edu/browse/JP-2202)._

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2202?focusedCommentId=538962#comment-538962):_

The WCS that exists in uncal and rate products is very minimal and doesn't include any information that includes distortions or anything to do with spectral dispersion. At best it contains only pointing information for the aperture reference point, so it's not obvious to me how accurate or trustworthy any computed RA/Dec source positions would be in those products. It's not until the assign_wcs step in calwebb_spec2 is applied that there is a full, accurate WCS object for the image, from which more accurate RA/Dec values can be obtained.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2202?focusedCommentId=539114#comment-539114):_

While working on the wfss_contam step, which also used simulated NIRCam direct and grism images produced with Mirage, I found that Mirage is using a newer set of NIRCam grism dispersion/trace coefficients than what's in the relatively old "specwcs" reference files in CRDS. So this results in a mismatch between the dispersed locations of grism spectra in the Mirage images and their computed/predicted locations that the cal pipeline computes based on the specwcs coefficients, and one of the major differences was noticeable offset in the cross-dispersion direction of the spectra. I was able to account for this by taking [Norbert Pirzkal](https://jira.stsci.edu/secure/ViewProfile.jspa?name=npirzkal)'s latest set of NIRCam grism trace/dispersion coeffs (used in Mirage) and putting them into a new set of "specwcs" ref files for CRDS. When I use those updated specwcs ref files in the cal pipeline the offsets go away. So the displacements you're seeing may have similar origin.

Unfortunately we haven't yet been able to install those updated specwcs ref files into CRDS, because it's been discovered that something has changed in the models that Nor uses for those coefficients, which result in the transforms not being able to round-trip properly. We need to work out that problem before we install the updated specwcs ref files into CRDS. I could make my local copies of them available to you, if desired, to see if they make a difference in the results you're getting. They need to be used when running the grism images through the assign_wcs step in the calwebb_spec2 pipeline.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2202?focusedCommentId=539457#comment-539457):_

The attached PDF showing examples indicates that your simulations were done with the F356W filter and GrismR. I don't know which instrument module you used (A or B), so I'm attaching the updated specwcs ref files for both modules (NIRCAM_F356W_modA_R.asdf and NIRCAM_F356W_modB_R.asdf). These need to be used in the assign_wcs step when running the calwebb_spec2 pipeline on the grism images, e.g.

strun calwebb_spec2 <your_grism_spec2_asn_file> --steps.assign_wcs.override_specwcs=NIRCam_F356W_modA_R.asdf

That should hopefully result in WCS transforms that give a better matchup to the object positions.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2202?focusedCommentId=539459#comment-539459):_

 [^NIRCAM_F356W_modB_R.asdf]  [^NIRCAM_F356W_modA_R.asdf]
