### ISSUE TITLE
Discrepancy between error arrays

### ISSUE THREAD

**Issue by kammerje** [spacetelescope/jwst#6308]
According to the [JWST pipeline manual](https://jwst-pipeline.readthedocs.io/en/latest/jwst/ramp_fitting/description.html) (see Error Propagation at the bottom of the page), the ERR array should be the square root of the sum of the VAR_POISSON and the VAR_RNOISE arrays. This is not the case in the rateints stage 1 pipeline product. The screenshot below illustrates this issue.
![Screen Shot 2021-08-27 at 4 27 09 AM](https://user-images.githubusercontent.com/32052440/131097423-a2eed446-9e8e-433e-8c13-beef4df4cf0b.png)

**Comment by stscijgbot-jp** [comment]
_Comment by [David Grumm](https://jira.stsci.edu/secure/ViewProfile.jspa?name=grumm) on [JIRA](https://jira.stsci.edu/browse/JP-2266?focusedCommentId=565562#comment-565562):_

Here is a summary of how the ERR arrays are calculated.

INTEGRATION-LEVEL COMPUTATIONS : 
For an integration, the variance of the slope due to read noise depends on the read noise variances of segments: 
 
var_int_RN = 1 / sum_seg( 1/var_seg_RN ), 

where the sum is over all the segments in the integration. 

Similarly, the variance of the slope due to Poisson noise depends on the Poisson variances of segments: 
 
var_int_PN = 1 / sum_seg( 1/var_seg_PN ) 

The combined variance of the slope due to both types of noise: 
 
var_int_COM = 1 / sum_seg( 1/( var_seg_RN + var_seg_PN )) 

In the rateints product, the values of var_int_RN and var_int_PN are output to the arrays VAR_RNOISE and VAR_POISSON. The values of sqrt( var_int_COM ) are output to the array ERR.

EXPOSURE-LEVEL COMPUTATIONS : 
For the entire exposure, the variance of the slope due to read noise depends on the variances of integrations: 
 
var_exp_RN = 1 / sum_int( 1/var_int_RN ), 

where the sum is over all the integrations in the exposure. 

Similarly, the variance of the slope due to Poisson noise depends on the variances of integrations: 
 
var_exp_PN = 1 / sum_int( 1/var_int_PN ) 

The combined variance of the slope due to both types of noise: 
 
var_exp_COM = sum_int( var_int_RN + var_int_PN )

In the rate product, the values of var_exp_RN and var_exp_PN are output to the arrays VAR_RNOISE and VAR_POISSON. The values of sqrt( var_exp_COM ) are output to the array ERR.

Note the difference in the form of the equations for var_int_COM and var_exp_COM.  They are correctly described in the documentation, but their difference may be the cause of the user's comment.  The equations used to calculate these variances were agreed upon in 2018. At that time, the validity of these equations was questionable, so they were considered to be provisional.  I am in the process of finding out if the method for calculation of these per-integration variances should be done differently.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2266?focusedCommentId=569361#comment-569361):_

After doing a detailed and careful read of the last couple sections of the ramp_fit RTD, I think [Jens Kammerer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=jkammerer) has a point. While the section of the docs that shows the detailed equations does make it explicit that the computation of the combined variances is a little different at the integration level than at the exposure level, the text in the final section (Error Propagation) makes the simple statement "The square-root of the combined variance of the slope due to both Poisson and read noise is written to the ERR extension" when talking about what's in the per-integration (rateints) product. This could easily be misinterpreted to mean that it's a simple sqrt(var_poisson + var_rnoise), as opposed to the somewhat more detailed and complicated expression given in the previous equations.

So I'm going to rewrite that last section of the docs to make it more explicit as to which items in the equations are being stored in the various products.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2266?focusedCommentId=569828#comment-569828):_

Fixed by #6715

**Comment by stscijgbot-jp** [comment]
_This issue is tracked on JIRA as [JP-2266](https://jira.stsci.edu/browse/JP-2266)._

**Comment by stscijgbot-jp** [comment]
_Comment by [David Grumm](https://jira.stsci.edu/secure/ViewProfile.jspa?name=grumm) on [JIRA](https://jira.stsci.edu/browse/JP-2266?focusedCommentId=565562#comment-565562):_

Here is a summary of how the ERR arrays are calculated.

INTEGRATION-LEVEL COMPUTATIONS : 
For an integration, the variance of the slope due to read noise depends on the read noise variances of segments: 
 
var_int_RN = 1 / sum_seg( 1/var_seg_RN ), 

where the sum is over all the segments in the integration. 

Similarly, the variance of the slope due to Poisson noise depends on the Poisson variances of segments: 
 
var_int_PN = 1 / sum_seg( 1/var_seg_PN ) 

The combined variance of the slope due to both types of noise: 
 
var_int_COM = 1 / sum_seg( 1/( var_seg_RN + var_seg_PN )) 

In the rateints product, the values of var_int_RN and var_int_PN are output to the arrays VAR_RNOISE and VAR_POISSON. The values of sqrt( var_int_COM ) are output to the array ERR.

EXPOSURE-LEVEL COMPUTATIONS : 
For the entire exposure, the variance of the slope due to read noise depends on the variances of integrations: 
 
var_exp_RN = 1 / sum_int( 1/var_int_RN ), 

where the sum is over all the integrations in the exposure. 

Similarly, the variance of the slope due to Poisson noise depends on the variances of integrations: 
 
var_exp_PN = 1 / sum_int( 1/var_int_PN ) 

The combined variance of the slope due to both types of noise: 
 
var_exp_COM = sum_int( var_int_RN + var_int_PN )

In the rate product, the values of var_exp_RN and var_exp_PN are output to the arrays VAR_RNOISE and VAR_POISSON. The values of sqrt( var_exp_COM ) are output to the array ERR.

Note the difference in the form of the equations for var_int_COM and var_exp_COM.  They are correctly described in the documentation, but their difference may be the cause of the user's comment.  The equations used to calculate these variances were agreed upon in 2018. At that time, the validity of these equations was questionable, so they were considered to be provisional.  I am in the process of finding out if the method for calculation of these per-integration variances should be done differently.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-2266?focusedCommentId=569828#comment-569828):_

Fixed by #6715
