### ISSUE TITLE
Questions about i2d extensions 

### ISSUE THREAD

**Issue by thomassimmer** [spacetelescope/jwst#6328]
My first question is about the ERR extension of i2d products. From what I understand in the pipeline and in the drizzle package, by default, the Inverse Variance weighting method (ivm) is used for the final drizzling in the "resample" step of calwebb_image3. This method uses only the read noise variance array of each input image. Could someone explain to me why? Secondly, I expected the ERR extension to be computed the way it is now, using only the read noise variance, but instead, the ERR extension is computed using read noise, Poisson, and flat variances. Could someone explain to me why?

My second question is about the WHT extension, the documentation (here https://jwst-pipeline.readthedocs.io/en/latest/jwst/data_products/science_products.html#resampled-2-d-data-i2d-and-s2d) says "WHT: 2-D weight image giving the relative weight of the output pixels (effectively a relative exposure time map)." However, from what I understood in the code, by default, i.e. using the ivm method, this extension seems to be the sum of all inverse read noise variances used in the computation of an output pixel. In this case, I do not understand why the documentation says it is a relative exposure time map. Could someone explain to me why? And a bonus question for the beginner that I am, would you mind telling me how this extension will be useful in the future?

I would like to mention that the current documentation does not mention yet the existence of the ERR, VAR_RNOISE, VAR_POISSON, and VAR_FLAT extensions.

ps: I arrived this year in the project and it is a pleasure for me to learn from everything you did here.

It may be a question for you @jdavies-st or @stscieisenhamer .

Thomas Simmer, IAS, France.

**Comment by jdavies-st** [comment]
Hi Thomas,

Using the photon noise (VAR_POISSON) for weighting is problematic, so we don't use it.  Inverse variance weighting is done using only the read noise variance as it is the closest thing we have that estimates the signal-independent noise at a given pixel for these multi-read IR detectors.  Currently we are not accounting for correlations in noise between reads or between pixels, though we have plans to for the future, enhanced pipeline.  @karllark can perhaps add more here.

Throughout the whole pipeline, the ERR term is the final RMS uncertainty from all noise sources so far tracked, for both _cal.fits file and _i2d.fits files.  Currently we track noise poisson noise, read noise and noise introduced from flat fielding.  In the future there will be more that we track, and ERR will have them all.  If you're interested in individual noise terms, that's what VAR_RNOISE, VAR_POISSON and VAR_FLAT are for.

Documentation indicating that WHT is effectively an exposure time map is incorrect, and we'll have to update that.  That said, for multiple non-destructive reads as used in these IR detectors, read noise is actually the closest thing we have that correlates to "exposure time" per pixel, for given readout mode.  The idea of an exposure time map from single-exposure CCDs does just not translate well to multi-read IR detectors that fit up-the-ramp at each pixel.

Anyway, thanks for pointing that out.  We will fix the documentation.

Also, we do need to improve the organization of the documentation.  But discussion of the variance/noise extensions can be found in a few places:

https://jwst-pipeline.readthedocs.io/en/latest/jwst/error_propagation/main.html

https://jwst-pipeline.readthedocs.io/en/latest/jwst/data_products/science_products.html

https://jwst-pipeline.readthedocs.io/en/latest/jwst/ramp_fitting/description.html#error-propagation

**Comment by karllark** [comment]
> Using the photon noise (VAR_POISSON) for weighting is problematic, so we don't use it.

A bit more one why this is the case.  The main reason is that the poisson noise is estimated from the slope measurement and hence is thus biased by the measurement itself.   In other words, if the slope measurement is lower than the "truth" due to noise, then the estimate of the poisson noise will be also low.  In addition, the sampling of the PSF by the finite sized pixels also can cause biases - with many cases for JWST where the pixels undersample the PSF and this amplifies poisson weighting biases.

**Comment by karllark** [comment]
> Currently we are not accounting for correlations in noise between reads or between pixels, though we have plans to for the future, enhanced pipeline. @karllark can perhaps add more here

The architecture of the pipeline has been setup to allow for more complicated noise models to be used as we improve different pipeline steps *and* the reference files that are used.  For example, once we have measurements of the spatial correlations in the flat field, we can then use this information when computing imaging mosaics - taking into account the spatial correlations and the dithers to generate more accurate weights on and uncertainties for the mosaic.  An algorithm to do this has been developed, but is not implemented yet due to resource limitations (both in coding the algorithm and getting the necessary spatial correlations for the flat field reference files).

**Comment by karllark** [comment]
> Currently we are not accounting for correlations in noise between reads

This is not correct.  We are accounting for correlations between groups (e.g., reads) in a ramp when doing the slope fitting.  Specifically, the "optimal" weighting used in the linear least squares fitting include the correlation photon noise.  We do know how to include additional correlations between groups (say due to the dark subtraction), but this (again) requires improvements the dark reference files and switching to use Generalized Least Squares with an explicit covariance matrix for the ramp fitting.
