### ISSUE TITLE
Steps missing from data model meta.cal_step

### ISSUE THREAD

**Issue by skendrew** [spacetelescope/jwst#6469]
Sorry not sure how to best describe this. I am running MIRI TSO data through the detector1 pipeline (from a Jupyter notebook). From the pipeline output I can see that the first frame and last frame steps were skipped; as they should be. However when I look into the output data model ``rate_ints`` metadata using:

``rate_ints.meta.cal_step.firstframe`` I get ``None``. 

The ref pix step in contrast, which was also skipped, returns:

``rate_ints.meta.cal_step.refpix = 'SKIPPED'``

Is this expected behavior?

**Comment by hbushouse** [comment]
@skendrew Steps like firstframe and lastframe are set to be skipped in the pars-detector1pipeline parameter ref file, so they never get called by the detector1 pipeline at all and hence their step status also never gets set in the output (that's why you get a `None` value for `cal_step.firstframe` - the attribute just doesn't exist at all). Meanwhile it looks like the `refpix` was at least called by the pipeline, but then skipped for some reason, and hence the step status is set to `SKIPPED`. I don't think `refpix` is supposed to be skipped routinely for TSO data, so I'm not sure why it would've been. Perhaps there's some info in the processing log that might indicate why the step was skipped (the pipeline usually reports why).

**Comment by nden** [comment]
@skendrew Is this something we need to track down? Or can the issue be closed?

**Comment by skendrew** [comment]
I think this is okay @nden, thanks for checking in. It's a bit confusing that there are different ways a step can be skipped, i.e. not called at all vs. called but then skipped. But I don't think this is something that nees urgent fixing. 

(The refpix stepped doesn't get executed for subarray data, so that is why it would be skipped for these data.)

**Comment by hbushouse** [comment]
This is related to and being worked in https://jira.stsci.edu/browse/JP-2355. So closing this issue.
