### ISSUE TITLE
CRDS setup in README is confusing

### ISSUE THREAD

**Issue by jdavies-st** [spacetelescope/jwst#6977]
The CRDS setup says

https://github.com/spacetelescope/jwst/blob/abd9b566e4e12fad17c2ba30850fc98a91594c92/README.md?plain=1#L160-L164

It's not clear here in the text what if any the differences are.  Though looking at the contexts on the two servers, different contexts map to different actual changes in the reference files, and reference file names do not map between ops and pub to the same reffile.  Super confusing.  This is suggested here on jwst-docs:

https://jwst-docs.stsci.edu/jwst-science-calibration-pipeline-overview/jwst-data-calibration-reference-files#JWSTDataCalibrationReferenceFiles-crdsCalibrationReferenceDataSystem

From the above link, it seems as if pub might give us the latest reffiles, but it's not clear.  Can you give a description (so I can understand) which one I would want to use if I have the latest pubic release of `jwst` and want the latest reffiles that the instrument teams have delivered to CRDS that have passed regression tests and are now available.  I.e. what determines if a reffile goes into pub and not ops (or vice versa)?

And maybe update the above README (and docs) here as well?

Also, there's no description of the ops/pub differences in the CRDS documentation it seems.  I would expect that to be here

https://hst-crds.stsci.edu/static/users_guide/web_site_use.html

Thanks!

**Comment by hbushouse** [comment]
@jdavies-st  We welcome unsolicited PR's from experienced external contributors, so ...

**Comment by jdavies-st** [comment]
😂 

Yeah, but I don't actually understand the difference between the two servers.  They both seem to be up-to-date with each other within a day or two, and it seem the ops server gets files delivered (and new default operation contexts set) before the pub one.

Is the pub one there in case there are breaking changes with respect to CRDS in released versions of `jwst` that haven't made it to ops yet?  Something that hasn't happened yet?

**Comment by jdavies-st** [comment]
1) I use the latest released version of `jwst` and I want the latest reffiles compatible with it.  Which do I use, ops or pub?

2) What is a use case that would make me instead want to use pub over ops, given the above?

**Comment by hbushouse** [comment]
Need @stscieisenhamer to give the definitive 411 on CRDS-OPS vs. CRDS-PUB, but basically any routine ref file update that just contains updated/better calibration based on recent analysis can go into Ops immediately (and Pub at the same time), so that routine processing of data as they come down get the benefit of better calibration. If, on the other hand, a new/updated ref file depends on new/updated *software* to support it, it can be delivered to Pub as soon as there's a public software release to support it and then it goes to Ops when that software release gets installed into operations.

Unfortunately, because of the asynchronous nature of deliveries to Ops and Pub, the same calibration data can end up with different ref file versions in their file names on the two different servers, and conversely the same ref file version name on the two different servers can contain different versions of data within them. Which of course makes for a very confusing situation for everyone involved (including the developers and testers!).

**Comment by jdavies-st** [comment]
Thanks @hbushouse.  That's very clear.  I'll update your README quoting you.  =)

Btw, I've been using the very handy CRDS script

```
cron_sync --fetch-references --after-context jwst_0942.pmap
```

to keep our CRDS cache updated nightly here at MPIA.  Works great.  But I have to be very consistent of whether I sync ops or pub, as you say, it matters.  I'm using ops right now, but it seems that eventually it might be good to switch to pub.

Thanks!

**Comment by hbushouse** [comment]
It always takes 1-2 months before a public release of the jwst package (available via pypi or from github) is installed in operations, so that's the period of time when it's advantageous to use crds-pub in order to get the latest/greatest updates when doing off-line (re)processing. Once operations gets the latest release, then crds-ops gets updated more frequently than pub, hence it's better during those times to stick with crds-ops. Of course, as always, YMMV.

**Comment by stscieisenhamer** [comment]
Sorry @hbushouse for jumping in on this late. @hbushouse is right: `pub` allows us to get things to-the-public sooner without having to depend on OPS versions.

**Comment by hbushouse** [comment]
but at the same time it seems as if once a new release gets installed in operations and crds-ops gets synched to have all the latest/greatest ref files to support that release, then routine updates to ref files only go to crds-ops for the next 2-3 months while the next software release is being developed, without them going to crds-pub. It seems crds-pub only gets updated (again in a mad dash all at once) right when we make the next public release of software. Is that true or is my memory clouded and/or jaded?

**Comment by stscieisenhamer** [comment]
Routine releases go to both OPS and PUB, though it is not immediate; processes are getting improved on this aspect.

**Comment by hbushouse** [comment]
CRDS-PUB is dead. Long live CRDS-OPS.
