### ISSUE TITLE
remove the `py` library

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#7310]
_Issue [JP-2981](https://jira.stsci.edu/browse/JP-2981) was created on JIRA by [Jonathan Eisenhamer](https://jira.stsci.edu/secure/ViewProfile.jspa?name=eisenham):_

Github alerted to the use of a vulnerable library, `py`, found in the `jwst` repo.

It appears in the `sdp-requirements.txt` file.

According to pypi, this library is in "maintenance mode" and should not be used in new code. The vulnerable versions, as reported by Github, is <=1.11.0. Well, the last version is 1.11.0.

This appears to be just a development support library, implying that production code should not need it.

Action is to find out why this is being imported and remove, if possible.

**Comment by jdavies-st** [comment]
This got installed because `pytest<=7.1.3` required it.  Grab previous, populated version of `requirements-sdp.txt`:

```
$ pip install -r requirements-sdp.txt
$ pip install pipdeptree
$ pipdeptree | less
...
  - pytest [required: >=3, installed: 7.1.3]
    - attrs [required: >=19.2.0, installed: 22.1.0]
    - iniconfig [required: Any, installed: 1.1.1]
    - packaging [required: Any, installed: 21.3]
      - pyparsing [required: >=2.0.2,!=3.0.5, installed: 3.0.9]
    - pluggy [required: >=0.12,<2.0, installed: 1.0.0]
    - py [required: >=1.8.2, installed: 1.11.0]
    - tomli [required: >=1.0.0, installed: 2.0.1]
...
```

It was removed as a dependency in `pytest 7.2.0`.

https://github.com/pytest-dev/pytest/commit/19dda7c9bdc8ef71c792e0f77a9595bfad8d9248#diff-63a9c44a44acf85fea213a857769990937107cf072831e1a26808cfde9d096b9L68

This does raise an interesting issue though:  the `[test]` dependencies are not actually runtime dependencies that need to be packed up for DMS/SDP use.  They are only there because they are needed to run the nightly regression tests which trigger the packaging.  So one could imagine instead of doing the current

https://github.com/spacetelescope/jwst/blob/4798525f79ff200d02a244cfb2e8cd59ac3f6fd1/requirements-sdp.txt#L13-L16

to generate `requirements-sdp.txt` one could instead do simply `pip install -e .` and then subsequently in the jenkins job install the `[test]` extras, but don't pin them.  Though if one wanted that to carry through to DMS, you would also have to do the env snapshot first, before install `[test]` extras.

Finally, I see the above instructions are not correct for generating the `requirements-sdp.txt` as it looks like `"jwst.git"` is no longer in the list to be removed.  That's not great.

https://github.com/spacetelescope/jwst/blob/4798525f79ff200d02a244cfb2e8cd59ac3f6fd1/requirements-sdp.txt#L16

`requirements-sdp.txt` should never self-reference the `jwst` package.

https://github.com/spacetelescope/jwst/blob/4798525f79ff200d02a244cfb2e8cd59ac3f6fd1/requirements-sdp.txt#L47

**Comment by jdavies-st** [comment]
Actually, I don't know why the jwst package was included in requirements-sdp.txt.  It shouldn't be, it gets generated by default in the Jenkins utilities upon successful test completion.

And including the `[test]` dependencies is not a problem (has not been) for SDP.  If its not broke, don't fix it, especially since the Jenkins stuff is difficult to deal with and it currently works.

Feel free to close this issue if resolved.

**Comment by jdavies-st** [comment]
This is resolved and can be closed, though since it is linked to a Jira ticket, I'll leave the resolving/closing to someone else.
