### ISSUE TITLE
Config parameter 'suffix': the value "False" is of the wrong type.

### ISSUE THREAD

**Issue by keflavich** [spacetelescope/jwst#7469]
I encountered the error below when running `Image2Pipeline`.  It seems to be a return of https://github.com/spacetelescope/jwst/issues/4241, which was resolved by saying "don't reuse instances of steps".  

There is still some underlying issue in which `Image2Pipeline.suffix` is being changed from `None` to `False`.  Additionally, this usage pattern should be more clearly documented; while most of the example notebooks I've seen adopt a pattern that avoids this issue by defining a new pipeline instance each time one is used, I didn't find an explanation of that pattern and (wrongly) assumed it was OK to reuse instances.

```
File "/orange/adamginsburg/jwst/brick/reduction/PipelineRerunNIRCAM-LONG.py", line 178, in main  

img2(member['expname'].replace("_cal.fits", "_rate.fits"))  
File "/orange/adamginsburg/miniconda3/envs/python39/lib/python3.9/site-packages/stpipe/step.py", line 406, in run    

f'Step {self.name} parameters are: {self.get_pars()}'  
File "/orange/adamginsburg/miniconda3/envs/python39/lib/python3.9/site-packages/stpipe/pipeline.py", line 322, in get_pars

pars = super().get_pars(full_spec=full_spec)  
File "/orange/adamginsburg/miniconda3/envs/python39/lib/python3.9/site-packages/stpipe/step.py", line 1267, in get_pars    

pars = config_parser.config_from_dict(instance_pars, spec, allow_missing=True)  
File "/orange/adamginsburg/miniconda3/envs/python39/lib/python3.9/site-packages/stpipe/config_parser.py", line 288, in config_from_dict    

validate(config, spec, root_dir=root_dir, allow_missing=allow_missing)  
File "/orange/adamginsburg/miniconda3/envs/python39/lib/python3.9/site-packages/stpipe/config_parser.py", line 377, in validate    

raise ValidationError('\n'.join(messages))ValidationError: Config parameter 'suffix': the value "False" is of the wrong type.
```

**Comment by tapastro** [comment]
Hi Adam,

The usage pattern of reusing a pipeline instance is not well documented as it is not recommended - see:

https://jwst-pipeline.readthedocs.io/en/latest/jwst/user_documentation/running_pipeline_python.html

Link in the note at the beginning of that page: https://jwst-pipeline.readthedocs.io/en/latest/jwst/user_documentation/running_pipeline_python.html#python-run-vs-call

Using direct invocation of a pipeline via e.g. `Spec2Pipeline(input)` or via .run() as `Spec2Pipeline.run(input)` ignores parameter specifications held in parameter reference files which have been determined by the instrument teams to be the best choices for data reduction. Our documentation recommends the use of .call(), which internally builds a new instance each time it is invoked, avoiding this problem entirely. If you see a notebook that recommends otherwise, you are welcome to file an issue against the repository holding that notebook and recommend they follow our documentation.

**Comment by tapastro** [comment]
The description of how to override parameters is in the link I provided.

The error message has no intent, and it can be fixed - I will file a ticket to address it.

**Comment by hbushouse** [comment]
How should we regard the status of this? Is the additional understanding of the use of the `.call` method instead of `.run` sufficient to allow us to close this issue?  If updates to the INS-provided notebooks is necessary, that's out of our hands.

**Comment by nden** [comment]
No further communication so I'm closing the issue. If necessary please open a new one.
