### ISSUE TITLE
JWST CRDS_PATH for offsite user?

### ISSUE THREAD

**Issue by meithne38** [spacetelescope/jwst#7695]
2023-07-05 13:39:03,908 - CRDS - ERROR -  (FATAL) CRDS server connection and cache load FAILED.  Cannot continue.
 See https://hst-crds.stsci.edu/docs/cmdline_bestrefs/ or https://jwst-crds.stsci.edu/docs/cmdline_bestrefs/
 for more information on configuring CRDS,  particularly CRDS_PATH and CRDS_SERVER_URL. : [Errno 2] No such file or directory: '/mypath/crds_cache/config/jwst/server_config'

I created a crds_cache directory manually but it is empty. How do I populate it with the necessary reference files?

**Comment by stscieisenhamer** [comment]
Greetings! Sorry to hear that you are having issues in accessing the CRDS content.

I am presuming the context in which you are getting the above error is that you are attempting to run one of the JWST pipelines, using the command `strun`.  If this is not the case, please expand on what you were doing that was attempting access to the CRDS server.

To start, please review the setup documentation that can be found at

https://jwst-pipeline.readthedocs.io/en/latest/jwst/user_documentation/reference_files_crds.html#crds-servers

If you believe you have setup the environment variables appropriately, try the following commands and add the results as a comment to this issue. The commands are
```
$ echo $CRDS_PATH
$ echo $CRDS_SERVER_URL
$ crds list --status
```
Once I know the output from the above, we can further explore what the issue is.

**Comment by stscieisenhamer** [comment]
Presuming issue has resolved itself.

Please feel free to file another if this, or any other, issue arises.
