### ISSUE TITLE
Github pre-releases aren't getting pushed to pypi

### ISSUE THREAD

**Issue by jdavies-st** [spacetelescope/jwst#8154]
Versions 1.13.0 and 1.13.1 of `jwst` are labelled as "pre-release" releases on Github.  This results in them not getting pushed to pypi.  So there are now tagged minor and patch releases on Github not installable via `pip install jwst==1.13.1`.  Is this intended?

**Comment by hbushouse** [comment]
Yes, it's intended, because of a situation with reference files. The 1.13.x releases contain the new MIRI "emicorr" step in the Detector1 pipeline, but the reference file information for it only exists in CRDS_TEST. The CRDS code itself needs an update in order to support the new ref file over in CRDS_OPS. So in order to avoid getting lots of questions from external users as to why the Detector1 pipeline crashes on them when they "pip install jwst==1.13.x" we intentionally kept them off of pypi (so they aren't quite as visible or as easily accessible, at least for now).

**Comment by jdavies-st** [comment]
Thanks Howard!  Closing this issue.
