### ISSUE TITLE
Save MRS indermediate product - un-distrorsion data

### ISSUE THREAD

**Issue by NicolasMonnier** [spacetelescope/jwst#8169]
Dear Team,

When running the entire pipeline, it is possible to save intermediate products or modify the reference coordinates of the resulting cube. 

With MRS, it is possible to obtain the calibrated instrument data at the output of stage 2 (see figure 1 below) or the data cube after correction of distortion and data interpolation. 

In my case, I'd like to be able to save the intermediate file: the distortion-corrected output before interpolating the data into a cube image (see Figure 2 to see an example of what it should look like). However, I didn't find any way to save this intermediate product. 

<img src="https://github.com/spacetelescope/jwst/assets/11629777/4ce95ab1-6baa-43fd-8838-43da1a2e09a1" width="250" height="250">

Figure 1 : example of calibrated data. Output of stage 2. Distortion is not corrected.

<img src="https://github.com/spacetelescope/jwst/assets/11629777/cad23c85-06d2-488c-9bee-b2d1dc0d1acd" width="250" height="250">

Figure 2 : example of distortion-corrected data --> Data product I'd like to save.

Is there any way or option to set in order to save this intermediate data product ? 

Thanks,
Nicolas

**Comment by hbushouse** [comment]
No such distortion-corrected 2D product is ever created by any of the pipeline steps. The distortion (and all other WCS-related) information is attached to the 2D images by the assign_wcs step, but is only ever applied when building a 3D cube, thus resulting in a rectified (distortion free) cube. The 3D cube is created by populating a distortion-free 3D WCS grid, based on the overlaps of all the 2D images, and then the distortion information is used to directly resample pixels from the 2D image into the 3D spaxels - no intermediate steps.

**Comment by NicolasMonnier** [comment]
> The rationale is that creating rectified 2D images and then resampling them to the rectified 3D cube would involve TWO resamplings of the data, which is undesirable.

That makes sense within the framework of the pipeline.


As I understand, there is no way with the pipeline to obtain such intermediate files. 
Then, is it possible to do it on my own from the output of stage 2 (figure 1 in my previous comment) ? 
Information about distortion is stored in the reference file, right?

**Comment by drlaw1558** [comment]
You could certainly write code to create your Figure 2 from Figure 1 if you wanted; all of the WCS information for each detector pixel is stored in the cal.fits files.  I.e.,

from jwst import datamodels
model=datamodels.open('myfile_cal.fits')
ra,dec,wave=model.meta.wcs.transform('detector', 'world', x, y)

You'd have to make some choices about how you wanted to do the resampling.

You might also be interested in the 'ifualign' cubes created from single cal.fits files.  Essentially, these will be very nearly the same thing as your Figure 2, just formatted as a 3d cube instead (i.e., rectified slices arranged next to each other on the sky instead of discontinuously on the detector).
