### ISSUE TITLE
coronography unit test failures on Mac only

### ISSUE THREAD

**Issue by stscijgbot-jp** [spacetelescope/jwst#8465]
_Issue [JP-3614](https://jira.stsci.edu/browse/JP-3614) was created on JIRA by [Ned Molter](https://jira.stsci.edu/secure/ViewProfile.jspa?name=emolter):_

The test jwst/coron/tests/test_coron.py::test_align_array started showing 
AssertionError: Not equal to tolerance rtol=1e-07, atol=1e-06 a few days ago when GitHub Actions runs the unit test suite for MacOS py311.
 
The differences are pretty small: Max absolute difference: 9.8773848e-06, Max relative difference: 4.67009943e-05.  However, it would be good to figure out why this happened (e.g., a numpy/scipy release) and ensure that there are no qualitative differences to worry about here before simply increasing the tolerances.

**Comment by braingram** [comment]
See: https://github.com/spacetelescope/jwst/pull/8440

The differences from the `leastsq` fit are relatively small. However the tolerances for the test had to be raised considerably (see https://github.com/spacetelescope/jwst/pull/8439) due to how the test is calculated.

I had some hope that scipy dev fixed this (as there were other leastsq issues). However the last time I checked (sometime last week) the nightly version still caused this test to fail.

**Comment by stscijgbot-jp** [comment]
_Comment by [Howard Bushouse](https://jira.stsci.edu/secure/ViewProfile.jspa?name=bushouse) on [JIRA](https://jira.stsci.edu/browse/JP-3614?focusedCommentId=699870#comment-699870):_

Fixed by #8490
